// Generated by scripts/build-reading-library.mjs
window.IBALL_CET6_READING_PAPERS = [
  {
    "id": "2026-06-3",
    "label": "2026 年 6 月 · 第 3 套",
    "year": 2026,
    "month": 6,
    "set": 3,
    "file": "./cet6-data/2026-06-3.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 39,
    "questionCount": 30,
    "cueCount": 66,
    "phraseCount": 156,
    "title": "2026 年 6 月六级阅读第 3 套"
  },
  {
    "id": "2026-06-2",
    "label": "2026 年 6 月 · 第 2 套",
    "year": 2026,
    "month": 6,
    "set": 2,
    "file": "./cet6-data/2026-06-2.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 33,
    "questionCount": 30,
    "cueCount": 57,
    "phraseCount": 131,
    "title": "2026 年 6 月六级阅读第 2 套"
  },
  {
    "id": "2026-06-1",
    "label": "2026 年 6 月 · 第 1 套",
    "year": 2026,
    "month": 6,
    "set": 1,
    "file": "./cet6-data/2026-06-1.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 34,
    "questionCount": 30,
    "cueCount": 58,
    "phraseCount": 136,
    "title": "2026 年 6 月六级阅读第 1 套"
  },
  {
    "id": "2025-12-3",
    "label": "2025 年 12 月 · 第 3 套",
    "year": 2025,
    "month": 12,
    "set": 3,
    "file": "./cet6-data/2025-12-3.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 38,
    "questionCount": 30,
    "cueCount": 67,
    "phraseCount": 151,
    "title": "2025 年 12 月六级阅读第 3 套"
  },
  {
    "id": "2025-12-2",
    "label": "2025 年 12 月 · 第 2 套",
    "year": 2025,
    "month": 12,
    "set": 2,
    "file": "./cet6-data/2025-12-2.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 39,
    "questionCount": 30,
    "cueCount": 63,
    "phraseCount": 156,
    "title": "2025 年 12 月六级阅读第 2 套"
  },
  {
    "id": "2025-12-1",
    "label": "2025 年 12 月 · 第 1 套",
    "year": 2025,
    "month": 12,
    "set": 1,
    "file": "./cet6-data/2025-12-1.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 37,
    "questionCount": 30,
    "cueCount": 60,
    "phraseCount": 148,
    "title": "2025 年 12 月六级阅读第 1 套"
  },
  {
    "id": "2025-06-3",
    "label": "2025 年 6 月 · 第 3 套",
    "year": 2025,
    "month": 6,
    "set": 3,
    "file": "./cet6-data/2025-06-3.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 37,
    "questionCount": 30,
    "cueCount": 59,
    "phraseCount": 148,
    "title": "2025 年 6 月六级阅读第 3 套"
  },
  {
    "id": "2025-06-2",
    "label": "2025 年 6 月 · 第 2 套",
    "year": 2025,
    "month": 6,
    "set": 2,
    "file": "./cet6-data/2025-06-2.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 39,
    "questionCount": 30,
    "cueCount": 72,
    "phraseCount": 153,
    "title": "2025 年 6 月六级阅读第 2 套"
  },
  {
    "id": "2025-06-1",
    "label": "2025 年 6 月 · 第 1 套",
    "year": 2025,
    "month": 6,
    "set": 1,
    "file": "./cet6-data/2025-06-1.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 43,
    "questionCount": 30,
    "cueCount": 48,
    "phraseCount": 172,
    "title": "2025 年 6 月六级阅读第 1 套"
  },
  {
    "id": "2024-12-3",
    "label": "2024 年 12 月 · 第 3 套",
    "year": 2024,
    "month": 12,
    "set": 3,
    "file": "./cet6-data/2024-12-3.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 32,
    "questionCount": 30,
    "cueCount": 55,
    "phraseCount": 128,
    "title": "2024 年 12 月六级阅读第 3 套"
  },
  {
    "id": "2024-12-2",
    "label": "2024 年 12 月 · 第 2 套",
    "year": 2024,
    "month": 12,
    "set": 2,
    "file": "./cet6-data/2024-12-2.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 38,
    "questionCount": 30,
    "cueCount": 69,
    "phraseCount": 150,
    "title": "2024 年 12 月六级阅读第 2 套"
  },
  {
    "id": "2024-12-1",
    "label": "2024 年 12 月 · 第 1 套",
    "year": 2024,
    "month": 12,
    "set": 1,
    "file": "./cet6-data/2024-12-1.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 39,
    "questionCount": 30,
    "cueCount": 54,
    "phraseCount": 150,
    "title": "2024 年 12 月六级阅读第 1 套"
  },
  {
    "id": "2024-06-3",
    "label": "2024 年 6 月 · 第 3 套",
    "year": 2024,
    "month": 6,
    "set": 3,
    "file": "./cet6-data/2024-06-3.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 37,
    "questionCount": 30,
    "cueCount": 76,
    "phraseCount": 148,
    "title": "2024 年 6 月六级阅读第 3 套"
  },
  {
    "id": "2024-06-2",
    "label": "2024 年 6 月 · 第 2 套",
    "year": 2024,
    "month": 6,
    "set": 2,
    "file": "./cet6-data/2024-06-2.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 33,
    "questionCount": 30,
    "cueCount": 50,
    "phraseCount": 127,
    "title": "2024 年 6 月六级阅读第 2 套"
  },
  {
    "id": "2024-06-1",
    "label": "2024 年 6 月 · 第 1 套",
    "year": 2024,
    "month": 6,
    "set": 1,
    "file": "./cet6-data/2024-06-1.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 39,
    "questionCount": 30,
    "cueCount": 60,
    "phraseCount": 151,
    "title": "2024 年 6 月六级阅读第 1 套"
  },
  {
    "id": "2023-12-3",
    "label": "2023 年 12 月 · 第 3 套",
    "year": 2023,
    "month": 12,
    "set": 3,
    "file": "./cet6-data/2023-12-3.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 34,
    "questionCount": 30,
    "cueCount": 69,
    "phraseCount": 136,
    "title": "2023 年 12 月六级阅读第 3 套"
  },
  {
    "id": "2023-12-2",
    "label": "2023 年 12 月 · 第 2 套",
    "year": 2023,
    "month": 12,
    "set": 2,
    "file": "./cet6-data/2023-12-2.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 27,
    "questionCount": 30,
    "cueCount": 44,
    "phraseCount": 108,
    "title": "2023 年 12 月六级阅读第 2 套"
  },
  {
    "id": "2023-12-1",
    "label": "2023 年 12 月 · 第 1 套",
    "year": 2023,
    "month": 12,
    "set": 1,
    "file": "./cet6-data/2023-12-1.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 37,
    "questionCount": 30,
    "cueCount": 57,
    "phraseCount": 148,
    "title": "2023 年 12 月六级阅读第 1 套"
  },
  {
    "id": "2023-06-3",
    "label": "2023 年 6 月 · 第 3 套",
    "year": 2023,
    "month": 6,
    "set": 3,
    "file": "./cet6-data/2023-06-3.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 32,
    "questionCount": 30,
    "cueCount": 58,
    "phraseCount": 128,
    "title": "2023 年 6 月六级阅读第 3 套"
  },
  {
    "id": "2023-06-2",
    "label": "2023 年 6 月 · 第 2 套",
    "year": 2023,
    "month": 6,
    "set": 2,
    "file": "./cet6-data/2023-06-2.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 29,
    "questionCount": 30,
    "cueCount": 55,
    "phraseCount": 114,
    "title": "2023 年 6 月六级阅读第 2 套"
  },
  {
    "id": "2023-06-1",
    "label": "2023 年 6 月 · 第 1 套",
    "year": 2023,
    "month": 6,
    "set": 1,
    "file": "./cet6-data/2023-06-1.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 31,
    "questionCount": 30,
    "cueCount": 60,
    "phraseCount": 124,
    "title": "2023 年 6 月六级阅读第 1 套"
  },
  {
    "id": "2023-03-1",
    "label": "2023 年 3 月 · 第 1 套",
    "year": 2023,
    "month": 3,
    "set": 1,
    "file": "./cet6-data/2023-03-1.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 32,
    "questionCount": 30,
    "cueCount": 65,
    "phraseCount": 128,
    "title": "2023 年 3 月六级阅读第 1 套"
  },
  {
    "id": "2022-12-3",
    "label": "2022 年 12 月 · 第 3 套",
    "year": 2022,
    "month": 12,
    "set": 3,
    "file": "./cet6-data/2022-12-3.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 39,
    "questionCount": 30,
    "cueCount": 61,
    "phraseCount": 155,
    "title": "2022 年 12 月六级阅读第 3 套"
  },
  {
    "id": "2022-12-2",
    "label": "2022 年 12 月 · 第 2 套",
    "year": 2022,
    "month": 12,
    "set": 2,
    "file": "./cet6-data/2022-12-2.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 36,
    "questionCount": 30,
    "cueCount": 66,
    "phraseCount": 140,
    "title": "2022 年 12 月六级阅读第 2 套"
  },
  {
    "id": "2022-12-1",
    "label": "2022 年 12 月 · 第 1 套",
    "year": 2022,
    "month": 12,
    "set": 1,
    "file": "./cet6-data/2022-12-1.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 28,
    "questionCount": 30,
    "cueCount": 45,
    "phraseCount": 112,
    "title": "2022 年 12 月六级阅读第 1 套"
  },
  {
    "id": "2022-09-1",
    "label": "2022 年 9 月 · 第 1 套",
    "year": 2022,
    "month": 9,
    "set": 1,
    "file": "./cet6-data/2022-09-1.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 37,
    "questionCount": 30,
    "cueCount": 57,
    "phraseCount": 146,
    "title": "2022 年 9 月六级阅读第 1 套"
  },
  {
    "id": "2022-06-2",
    "label": "2022 年 6 月 · 第 2 套",
    "year": 2022,
    "month": 6,
    "set": 2,
    "file": "./cet6-data/2022-06-2.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 27,
    "questionCount": 30,
    "cueCount": 50,
    "phraseCount": 108,
    "title": "2022 年 6 月六级阅读第 2 套"
  },
  {
    "id": "2022-06-1",
    "label": "2022 年 6 月 · 第 1 套",
    "year": 2022,
    "month": 6,
    "set": 1,
    "file": "./cet6-data/2022-06-1.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 29,
    "questionCount": 30,
    "cueCount": 46,
    "phraseCount": 116,
    "title": "2022 年 6 月六级阅读第 1 套"
  },
  {
    "id": "2021-12-3",
    "label": "2021 年 12 月 · 第 3 套",
    "year": 2021,
    "month": 12,
    "set": 3,
    "file": "./cet6-data/2021-12-3.js",
    "pieceCount": 3,
    "missing": [
      "选词填空"
    ],
    "types": [
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 32,
    "questionCount": 20,
    "cueCount": 54,
    "phraseCount": 128,
    "title": "2021 年 12 月六级阅读第 3 套"
  },
  {
    "id": "2021-12-2",
    "label": "2021 年 12 月 · 第 2 套",
    "year": 2021,
    "month": 12,
    "set": 2,
    "file": "./cet6-data/2021-12-2.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 27,
    "questionCount": 30,
    "cueCount": 59,
    "phraseCount": 108,
    "title": "2021 年 12 月六级阅读第 2 套"
  },
  {
    "id": "2021-12-1",
    "label": "2021 年 12 月 · 第 1 套",
    "year": 2021,
    "month": 12,
    "set": 1,
    "file": "./cet6-data/2021-12-1.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 26,
    "questionCount": 30,
    "cueCount": 44,
    "phraseCount": 104,
    "title": "2021 年 12 月六级阅读第 1 套"
  },
  {
    "id": "2021-06-3",
    "label": "2021 年 6 月 · 第 3 套",
    "year": 2021,
    "month": 6,
    "set": 3,
    "file": "./cet6-data/2021-06-3.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 29,
    "questionCount": 30,
    "cueCount": 46,
    "phraseCount": 116,
    "title": "2021 年 6 月六级阅读第 3 套"
  },
  {
    "id": "2021-06-2",
    "label": "2021 年 6 月 · 第 2 套",
    "year": 2021,
    "month": 6,
    "set": 2,
    "file": "./cet6-data/2021-06-2.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 29,
    "questionCount": 30,
    "cueCount": 45,
    "phraseCount": 116,
    "title": "2021 年 6 月六级阅读第 2 套"
  },
  {
    "id": "2021-06-1",
    "label": "2021 年 6 月 · 第 1 套",
    "year": 2021,
    "month": 6,
    "set": 1,
    "file": "./cet6-data/2021-06-1.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 25,
    "questionCount": 30,
    "cueCount": 43,
    "phraseCount": 100,
    "title": "2021 年 6 月六级阅读第 1 套"
  },
  {
    "id": "2020-12-3",
    "label": "2020 年 12 月 · 第 3 套",
    "year": 2020,
    "month": 12,
    "set": 3,
    "file": "./cet6-data/2020-12-3.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 34,
    "questionCount": 30,
    "cueCount": 67,
    "phraseCount": 136,
    "title": "2020 年 12 月六级阅读第 3 套"
  },
  {
    "id": "2020-12-2",
    "label": "2020 年 12 月 · 第 2 套",
    "year": 2020,
    "month": 12,
    "set": 2,
    "file": "./cet6-data/2020-12-2.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 31,
    "questionCount": 30,
    "cueCount": 52,
    "phraseCount": 122,
    "title": "2020 年 12 月六级阅读第 2 套"
  },
  {
    "id": "2020-12-1",
    "label": "2020 年 12 月 · 第 1 套",
    "year": 2020,
    "month": 12,
    "set": 1,
    "file": "./cet6-data/2020-12-1.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 36,
    "questionCount": 30,
    "cueCount": 49,
    "phraseCount": 144,
    "title": "2020 年 12 月六级阅读第 1 套"
  },
  {
    "id": "2020-09-2",
    "label": "2020 年 9 月 · 第 2 套",
    "year": 2020,
    "month": 9,
    "set": 2,
    "file": "./cet6-data/2020-09-2.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 40,
    "questionCount": 30,
    "cueCount": 58,
    "phraseCount": 156,
    "title": "2020 年 9 月六级阅读第 2 套"
  },
  {
    "id": "2020-09-1",
    "label": "2020 年 9 月 · 第 1 套",
    "year": 2020,
    "month": 9,
    "set": 1,
    "file": "./cet6-data/2020-09-1.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 33,
    "questionCount": 30,
    "cueCount": 64,
    "phraseCount": 132,
    "title": "2020 年 9 月六级阅读第 1 套"
  },
  {
    "id": "2020-07-1",
    "label": "2020 年 7 月 · 第 1 套",
    "year": 2020,
    "month": 7,
    "set": 1,
    "file": "./cet6-data/2020-07-1.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 29,
    "questionCount": 30,
    "cueCount": 60,
    "phraseCount": 116,
    "title": "2020 年 7 月六级阅读第 1 套"
  },
  {
    "id": "2019-12-3",
    "label": "2019 年 12 月 · 第 3 套",
    "year": 2019,
    "month": 12,
    "set": 3,
    "file": "./cet6-data/2019-12-3.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 25,
    "questionCount": 30,
    "cueCount": 53,
    "phraseCount": 100,
    "title": "2019 年 12 月六级阅读第 3 套"
  },
  {
    "id": "2019-12-2",
    "label": "2019 年 12 月 · 第 2 套",
    "year": 2019,
    "month": 12,
    "set": 2,
    "file": "./cet6-data/2019-12-2.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 31,
    "questionCount": 30,
    "cueCount": 65,
    "phraseCount": 123,
    "title": "2019 年 12 月六级阅读第 2 套"
  },
  {
    "id": "2019-12-1",
    "label": "2019 年 12 月 · 第 1 套",
    "year": 2019,
    "month": 12,
    "set": 1,
    "file": "./cet6-data/2019-12-1.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 24,
    "questionCount": 30,
    "cueCount": 55,
    "phraseCount": 96,
    "title": "2019 年 12 月六级阅读第 1 套"
  },
  {
    "id": "2019-06-3",
    "label": "2019 年 6 月 · 第 3 套",
    "year": 2019,
    "month": 6,
    "set": 3,
    "file": "./cet6-data/2019-06-3.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 30,
    "questionCount": 30,
    "cueCount": 63,
    "phraseCount": 120,
    "title": "2019 年 6 月六级阅读第 3 套"
  },
  {
    "id": "2019-06-2",
    "label": "2019 年 6 月 · 第 2 套",
    "year": 2019,
    "month": 6,
    "set": 2,
    "file": "./cet6-data/2019-06-2.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 34,
    "questionCount": 30,
    "cueCount": 57,
    "phraseCount": 136,
    "title": "2019 年 6 月六级阅读第 2 套"
  },
  {
    "id": "2019-06-1",
    "label": "2019 年 6 月 · 第 1 套",
    "year": 2019,
    "month": 6,
    "set": 1,
    "file": "./cet6-data/2019-06-1.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 36,
    "questionCount": 30,
    "cueCount": 59,
    "phraseCount": 142,
    "title": "2019 年 6 月六级阅读第 1 套"
  },
  {
    "id": "2018-12-3",
    "label": "2018 年 12 月 · 第 3 套",
    "year": 2018,
    "month": 12,
    "set": 3,
    "file": "./cet6-data/2018-12-3.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 36,
    "questionCount": 30,
    "cueCount": 61,
    "phraseCount": 144,
    "title": "2018 年 12 月六级阅读第 3 套"
  },
  {
    "id": "2018-12-2",
    "label": "2018 年 12 月 · 第 2 套",
    "year": 2018,
    "month": 12,
    "set": 2,
    "file": "./cet6-data/2018-12-2.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 38,
    "questionCount": 30,
    "cueCount": 54,
    "phraseCount": 147,
    "title": "2018 年 12 月六级阅读第 2 套"
  },
  {
    "id": "2018-12-1",
    "label": "2018 年 12 月 · 第 1 套",
    "year": 2018,
    "month": 12,
    "set": 1,
    "file": "./cet6-data/2018-12-1.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 36,
    "questionCount": 30,
    "cueCount": 44,
    "phraseCount": 139,
    "title": "2018 年 12 月六级阅读第 1 套"
  },
  {
    "id": "2018-06-3",
    "label": "2018 年 6 月 · 第 3 套",
    "year": 2018,
    "month": 6,
    "set": 3,
    "file": "./cet6-data/2018-06-3.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 34,
    "questionCount": 30,
    "cueCount": 66,
    "phraseCount": 134,
    "title": "2018 年 6 月六级阅读第 3 套"
  },
  {
    "id": "2018-06-2",
    "label": "2018 年 6 月 · 第 2 套",
    "year": 2018,
    "month": 6,
    "set": 2,
    "file": "./cet6-data/2018-06-2.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 32,
    "questionCount": 30,
    "cueCount": 56,
    "phraseCount": 128,
    "title": "2018 年 6 月六级阅读第 2 套"
  },
  {
    "id": "2018-06-1",
    "label": "2018 年 6 月 · 第 1 套",
    "year": 2018,
    "month": 6,
    "set": 1,
    "file": "./cet6-data/2018-06-1.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 29,
    "questionCount": 30,
    "cueCount": 59,
    "phraseCount": 116,
    "title": "2018 年 6 月六级阅读第 1 套"
  },
  {
    "id": "2017-12-3",
    "label": "2017 年 12 月 · 第 3 套",
    "year": 2017,
    "month": 12,
    "set": 3,
    "file": "./cet6-data/2017-12-3.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 31,
    "questionCount": 30,
    "cueCount": 42,
    "phraseCount": 124,
    "title": "2017 年 12 月六级阅读第 3 套"
  },
  {
    "id": "2017-12-2",
    "label": "2017 年 12 月 · 第 2 套",
    "year": 2017,
    "month": 12,
    "set": 2,
    "file": "./cet6-data/2017-12-2.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 35,
    "questionCount": 30,
    "cueCount": 57,
    "phraseCount": 140,
    "title": "2017 年 12 月六级阅读第 2 套"
  },
  {
    "id": "2017-12-1",
    "label": "2017 年 12 月 · 第 1 套",
    "year": 2017,
    "month": 12,
    "set": 1,
    "file": "./cet6-data/2017-12-1.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 32,
    "questionCount": 30,
    "cueCount": 52,
    "phraseCount": 128,
    "title": "2017 年 12 月六级阅读第 1 套"
  },
  {
    "id": "2017-06-3",
    "label": "2017 年 6 月 · 第 3 套",
    "year": 2017,
    "month": 6,
    "set": 3,
    "file": "./cet6-data/2017-06-3.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 33,
    "questionCount": 30,
    "cueCount": 50,
    "phraseCount": 132,
    "title": "2017 年 6 月六级阅读第 3 套"
  },
  {
    "id": "2017-06-2",
    "label": "2017 年 6 月 · 第 2 套",
    "year": 2017,
    "month": 6,
    "set": 2,
    "file": "./cet6-data/2017-06-2.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 29,
    "questionCount": 30,
    "cueCount": 49,
    "phraseCount": 116,
    "title": "2017 年 6 月六级阅读第 2 套"
  },
  {
    "id": "2017-06-1",
    "label": "2017 年 6 月 · 第 1 套",
    "year": 2017,
    "month": 6,
    "set": 1,
    "file": "./cet6-data/2017-06-1.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 30,
    "questionCount": 30,
    "cueCount": 57,
    "phraseCount": 120,
    "title": "2017 年 6 月六级阅读第 1 套"
  },
  {
    "id": "2016-12-3",
    "label": "2016 年 12 月 · 第 3 套",
    "year": 2016,
    "month": 12,
    "set": 3,
    "file": "./cet6-data/2016-12-3.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 31,
    "questionCount": 30,
    "cueCount": 53,
    "phraseCount": 124,
    "title": "2016 年 12 月六级阅读第 3 套"
  },
  {
    "id": "2016-12-2",
    "label": "2016 年 12 月 · 第 2 套",
    "year": 2016,
    "month": 12,
    "set": 2,
    "file": "./cet6-data/2016-12-2.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 32,
    "questionCount": 30,
    "cueCount": 55,
    "phraseCount": 127,
    "title": "2016 年 12 月六级阅读第 2 套"
  },
  {
    "id": "2016-12-1",
    "label": "2016 年 12 月 · 第 1 套",
    "year": 2016,
    "month": 12,
    "set": 1,
    "file": "./cet6-data/2016-12-1.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 34,
    "questionCount": 30,
    "cueCount": 60,
    "phraseCount": 136,
    "title": "2016 年 12 月六级阅读第 1 套"
  },
  {
    "id": "2016-06-3",
    "label": "2016 年 6 月 · 第 3 套",
    "year": 2016,
    "month": 6,
    "set": 3,
    "file": "./cet6-data/2016-06-3.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 40,
    "questionCount": 30,
    "cueCount": 34,
    "phraseCount": 160,
    "title": "2016 年 6 月六级阅读第 3 套"
  },
  {
    "id": "2016-06-2",
    "label": "2016 年 6 月 · 第 2 套",
    "year": 2016,
    "month": 6,
    "set": 2,
    "file": "./cet6-data/2016-06-2.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 36,
    "questionCount": 30,
    "cueCount": 53,
    "phraseCount": 141,
    "title": "2016 年 6 月六级阅读第 2 套"
  },
  {
    "id": "2016-06-1",
    "label": "2016 年 6 月 · 第 1 套",
    "year": 2016,
    "month": 6,
    "set": 1,
    "file": "./cet6-data/2016-06-1.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 32,
    "questionCount": 30,
    "cueCount": 63,
    "phraseCount": 128,
    "title": "2016 年 6 月六级阅读第 1 套"
  },
  {
    "id": "2015-12-3",
    "label": "2015 年 12 月 · 第 3 套",
    "year": 2015,
    "month": 12,
    "set": 3,
    "file": "./cet6-data/2015-12-3.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 29,
    "questionCount": 30,
    "cueCount": 54,
    "phraseCount": 115,
    "title": "2015 年 12 月六级阅读第 3 套"
  },
  {
    "id": "2015-12-2",
    "label": "2015 年 12 月 · 第 2 套",
    "year": 2015,
    "month": 12,
    "set": 2,
    "file": "./cet6-data/2015-12-2.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 36,
    "questionCount": 30,
    "cueCount": 62,
    "phraseCount": 144,
    "title": "2015 年 12 月六级阅读第 2 套"
  },
  {
    "id": "2015-12-1",
    "label": "2015 年 12 月 · 第 1 套",
    "year": 2015,
    "month": 12,
    "set": 1,
    "file": "./cet6-data/2015-12-1.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 27,
    "questionCount": 30,
    "cueCount": 51,
    "phraseCount": 108,
    "title": "2015 年 12 月六级阅读第 1 套"
  },
  {
    "id": "2015-06-3",
    "label": "2015 年 6 月 · 第 3 套",
    "year": 2015,
    "month": 6,
    "set": 3,
    "file": "./cet6-data/2015-06-3.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 35,
    "questionCount": 30,
    "cueCount": 52,
    "phraseCount": 140,
    "title": "2015 年 6 月六级阅读第 3 套"
  },
  {
    "id": "2015-06-2",
    "label": "2015 年 6 月 · 第 2 套",
    "year": 2015,
    "month": 6,
    "set": 2,
    "file": "./cet6-data/2015-06-2.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 31,
    "questionCount": 30,
    "cueCount": 45,
    "phraseCount": 124,
    "title": "2015 年 6 月六级阅读第 2 套"
  },
  {
    "id": "2015-06-1",
    "label": "2015 年 6 月 · 第 1 套",
    "year": 2015,
    "month": 6,
    "set": 1,
    "file": "./cet6-data/2015-06-1.js",
    "pieceCount": 4,
    "missing": [],
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 26,
    "questionCount": 30,
    "cueCount": 51,
    "phraseCount": 104,
    "title": "2015 年 6 月六级阅读第 1 套"
  }
];
