// Generated by scripts/build-intensive-library.mjs
window.IBALL_INTENSIVE_PAPERS = [
  {
    "id": "2026-06-2",
    "label": "2026 年 6 月 · 第 2 套",
    "file": "./intensive-data/2026-06-2.js",
    "pieceCount": 8,
    "paragraphCount": 30,
    "grammarCount": 46,
    "phraseCount": 49,
    "questionCount": 25,
    "title": "2026 年 6 月四级听力第 2 套"
  },
  {
    "id": "2026-06-1",
    "label": "2026 年 6 月 · 第 1 套",
    "file": "./intensive-data/2026-06-1.js",
    "pieceCount": 8,
    "paragraphCount": 45,
    "grammarCount": 40,
    "phraseCount": 65,
    "questionCount": 25,
    "title": "2026 年 6 月四级听力第 1 套"
  },
  {
    "id": "2025-12-2",
    "label": "2025 年 12 月 · 第 2 套",
    "file": "./intensive-data/2025-12-2.js",
    "pieceCount": 8,
    "paragraphCount": 48,
    "grammarCount": 33,
    "phraseCount": 50,
    "questionCount": 25,
    "title": "2025 年 12 月四级听力第 2 套"
  },
  {
    "id": "2025-12-1",
    "label": "2025 年 12 月 · 第 1 套",
    "file": "./intensive-data/2025-12-1.js",
    "pieceCount": 8,
    "paragraphCount": 43,
    "grammarCount": 28,
    "phraseCount": 49,
    "questionCount": 25,
    "title": "2025 年 12 月四级听力第 1 套"
  },
  {
    "id": "2025-06-2",
    "label": "2025 年 6 月 · 第 2 套",
    "file": "./intensive-data/2025-06-2.js",
    "pieceCount": 8,
    "paragraphCount": 35,
    "grammarCount": 25,
    "phraseCount": 56,
    "questionCount": 25,
    "title": "2025 年 6 月四级听力第 2 套"
  },
  {
    "id": "2025-06-1",
    "label": "2025 年 6 月 · 第 1 套",
    "file": "./intensive-data/2025-06-1.js",
    "pieceCount": 8,
    "paragraphCount": 51,
    "grammarCount": 34,
    "phraseCount": 54,
    "questionCount": 25,
    "title": "2025 年 6 月四级听力第 1 套"
  },
  {
    "id": "2024-12-2",
    "label": "2024 年 12 月 · 第 2 套",
    "file": "./intensive-data/2024-12-2.js",
    "pieceCount": 8,
    "paragraphCount": 34,
    "grammarCount": 25,
    "phraseCount": 53,
    "questionCount": 25,
    "title": "2024 年 12 月四级听力第 2 套"
  },
  {
    "id": "2024-12-1",
    "label": "2024 年 12 月 · 第 1 套",
    "file": "./intensive-data/2024-12-1.js",
    "pieceCount": 8,
    "paragraphCount": 38,
    "grammarCount": 29,
    "phraseCount": 68,
    "questionCount": 25,
    "title": "2024 年 12 月四级听力第 1 套"
  },
  {
    "id": "2024-06-2",
    "label": "2024 年 6 月 · 第 2 套",
    "file": "./intensive-data/2024-06-2.js",
    "pieceCount": 8,
    "paragraphCount": 45,
    "grammarCount": 31,
    "phraseCount": 69,
    "questionCount": 25,
    "title": "2024 年 6 月四级听力第 2 套"
  },
  {
    "id": "2024-06-1",
    "label": "2024 年 6 月 · 第 1 套",
    "file": "./intensive-data/2024-06-1.js",
    "pieceCount": 8,
    "paragraphCount": 35,
    "grammarCount": 34,
    "phraseCount": 66,
    "questionCount": 25,
    "title": "2024 年 6 月四级听力第 1 套"
  },
  {
    "id": "2023-12-2",
    "label": "2023 年 12 月 · 第 2 套",
    "file": "./intensive-data/2023-12-2.js",
    "pieceCount": 8,
    "paragraphCount": 39,
    "grammarCount": 32,
    "phraseCount": 63,
    "questionCount": 25,
    "title": "2023 年 12 月四级听力第 2 套"
  },
  {
    "id": "2023-12-1",
    "label": "2023 年 12 月 · 第 1 套",
    "file": "./intensive-data/2023-12-1.js",
    "pieceCount": 8,
    "paragraphCount": 44,
    "grammarCount": 37,
    "phraseCount": 67,
    "questionCount": 25,
    "title": "2023 年 12 月四级听力第 1 套"
  },
  {
    "id": "2023-06-2",
    "label": "2023 年 6 月 · 第 2 套",
    "file": "./intensive-data/2023-06-2.js",
    "pieceCount": 8,
    "paragraphCount": 55,
    "grammarCount": 46,
    "phraseCount": 66,
    "questionCount": 25,
    "title": "2023 年 6 月四级听力第 2 套"
  },
  {
    "id": "2023-06-1",
    "label": "2023 年 6 月 · 第 1 套",
    "file": "./intensive-data/2023-06-1.js",
    "pieceCount": 8,
    "paragraphCount": 54,
    "grammarCount": 36,
    "phraseCount": 60,
    "questionCount": 25,
    "title": "2023 年 6 月四级听力第 1 套"
  },
  {
    "id": "2023-03-1",
    "label": "2023 年 3 月 · 第 1 套",
    "file": "./intensive-data/2023-03-1.js",
    "pieceCount": 8,
    "paragraphCount": 37,
    "grammarCount": 47,
    "phraseCount": 46,
    "questionCount": 25,
    "title": "2023 年 3 月四级听力第 1 套"
  },
  {
    "id": "2022-12-2",
    "label": "2022 年 12 月 · 第 2 套",
    "file": "./intensive-data/2022-12-2.js",
    "pieceCount": 8,
    "paragraphCount": 53,
    "grammarCount": 29,
    "phraseCount": 63,
    "questionCount": 25,
    "title": "2022 年 12 月四级听力第 2 套"
  },
  {
    "id": "2022-12-1",
    "label": "2022 年 12 月 · 第 1 套",
    "file": "./intensive-data/2022-12-1.js",
    "pieceCount": 8,
    "paragraphCount": 60,
    "grammarCount": 19,
    "phraseCount": 49,
    "questionCount": 25,
    "title": "2022 年 12 月四级听力第 1 套"
  },
  {
    "id": "2022-09-1",
    "label": "2022 年 9 月 · 第 1 套",
    "file": "./intensive-data/2022-09-1.js",
    "pieceCount": 8,
    "paragraphCount": 50,
    "grammarCount": 28,
    "phraseCount": 67,
    "questionCount": 25,
    "title": "2022 年 9 月四级听力第 1 套"
  },
  {
    "id": "2022-06-1",
    "label": "2022 年 6 月 · 第 1 套",
    "file": "./intensive-data/2022-06-1.js",
    "pieceCount": 8,
    "paragraphCount": 59,
    "grammarCount": 34,
    "phraseCount": 76,
    "questionCount": 25,
    "title": "2022 年 6 月四级听力第 1 套"
  }
];
