// Generated by scripts/build-reading-library.mjs
window.IBALL_READING_PAPERS = [
  {
    "id": "2026-06-3",
    "label": "2026 年 6 月 · 第 3 套",
    "year": 2026,
    "month": 6,
    "set": 3,
    "file": "./reading-data/2026-06-3.js",
    "pieceCount": 4,
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 29,
    "questionCount": 30,
    "cueCount": 63,
    "phraseCount": 116,
    "title": "2026 年 6 月四级阅读第 3 套"
  },
  {
    "id": "2026-06-2",
    "label": "2026 年 6 月 · 第 2 套",
    "year": 2026,
    "month": 6,
    "set": 2,
    "file": "./reading-data/2026-06-2.js",
    "pieceCount": 4,
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 32,
    "questionCount": 30,
    "cueCount": 62,
    "phraseCount": 128,
    "title": "2026 年 6 月四级阅读第 2 套"
  },
  {
    "id": "2026-06-1",
    "label": "2026 年 6 月 · 第 1 套",
    "year": 2026,
    "month": 6,
    "set": 1,
    "file": "./reading-data/2026-06-1.js",
    "pieceCount": 4,
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 35,
    "questionCount": 30,
    "cueCount": 47,
    "phraseCount": 137,
    "title": "2026 年 6 月四级阅读第 1 套"
  },
  {
    "id": "2025-12-3",
    "label": "2025 年 12 月 · 第 3 套",
    "year": 2025,
    "month": 12,
    "set": 3,
    "file": "./reading-data/2025-12-3.js",
    "pieceCount": 4,
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 33,
    "questionCount": 30,
    "cueCount": 43,
    "phraseCount": 130,
    "title": "2025 年 12 月四级阅读第 3 套"
  },
  {
    "id": "2025-12-2",
    "label": "2025 年 12 月 · 第 2 套",
    "year": 2025,
    "month": 12,
    "set": 2,
    "file": "./reading-data/2025-12-2.js",
    "pieceCount": 4,
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 29,
    "questionCount": 30,
    "cueCount": 54,
    "phraseCount": 111,
    "title": "2025 年 12 月四级阅读第 2 套"
  },
  {
    "id": "2025-12-1",
    "label": "2025 年 12 月 · 第 1 套",
    "year": 2025,
    "month": 12,
    "set": 1,
    "file": "./reading-data/2025-12-1.js",
    "pieceCount": 4,
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 31,
    "questionCount": 30,
    "cueCount": 46,
    "phraseCount": 124,
    "title": "2025 年 12 月四级阅读第 1 套"
  },
  {
    "id": "2025-06-3",
    "label": "2025 年 6 月 · 第 3 套",
    "year": 2025,
    "month": 6,
    "set": 3,
    "file": "./reading-data/2025-06-3.js",
    "pieceCount": 4,
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 31,
    "questionCount": 30,
    "cueCount": 62,
    "phraseCount": 124,
    "title": "2025 年 6 月四级阅读第 3 套"
  },
  {
    "id": "2025-06-2",
    "label": "2025 年 6 月 · 第 2 套",
    "year": 2025,
    "month": 6,
    "set": 2,
    "file": "./reading-data/2025-06-2.js",
    "pieceCount": 4,
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 25,
    "questionCount": 30,
    "cueCount": 45,
    "phraseCount": 100,
    "title": "2025 年 6 月四级阅读第 2 套"
  },
  {
    "id": "2025-06-1",
    "label": "2025 年 6 月 · 第 1 套",
    "year": 2025,
    "month": 6,
    "set": 1,
    "file": "./reading-data/2025-06-1.js",
    "pieceCount": 4,
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 31,
    "questionCount": 30,
    "cueCount": 47,
    "phraseCount": 124,
    "title": "2025 年 6 月四级阅读第 1 套"
  },
  {
    "id": "2024-12-3",
    "label": "2024 年 12 月 · 第 3 套",
    "year": 2024,
    "month": 12,
    "set": 3,
    "file": "./reading-data/2024-12-3.js",
    "pieceCount": 4,
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 34,
    "questionCount": 30,
    "cueCount": 57,
    "phraseCount": 134,
    "title": "2024 年 12 月四级阅读第 3 套"
  },
  {
    "id": "2024-12-2",
    "label": "2024 年 12 月 · 第 2 套",
    "year": 2024,
    "month": 12,
    "set": 2,
    "file": "./reading-data/2024-12-2.js",
    "pieceCount": 4,
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 32,
    "questionCount": 30,
    "cueCount": 51,
    "phraseCount": 125,
    "title": "2024 年 12 月四级阅读第 2 套"
  },
  {
    "id": "2024-12-1",
    "label": "2024 年 12 月 · 第 1 套",
    "year": 2024,
    "month": 12,
    "set": 1,
    "file": "./reading-data/2024-12-1.js",
    "pieceCount": 4,
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 28,
    "questionCount": 30,
    "cueCount": 49,
    "phraseCount": 110,
    "title": "2024 年 12 月四级阅读第 1 套"
  },
  {
    "id": "2024-06-3",
    "label": "2024 年 6 月 · 第 3 套",
    "year": 2024,
    "month": 6,
    "set": 3,
    "file": "./reading-data/2024-06-3.js",
    "pieceCount": 4,
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 25,
    "questionCount": 30,
    "cueCount": 47,
    "phraseCount": 100,
    "title": "2024 年 6 月四级阅读第 3 套"
  },
  {
    "id": "2024-06-2",
    "label": "2024 年 6 月 · 第 2 套",
    "year": 2024,
    "month": 6,
    "set": 2,
    "file": "./reading-data/2024-06-2.js",
    "pieceCount": 4,
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 26,
    "questionCount": 30,
    "cueCount": 55,
    "phraseCount": 104,
    "title": "2024 年 6 月四级阅读第 2 套"
  },
  {
    "id": "2024-06-1",
    "label": "2024 年 6 月 · 第 1 套",
    "year": 2024,
    "month": 6,
    "set": 1,
    "file": "./reading-data/2024-06-1.js",
    "pieceCount": 4,
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 27,
    "questionCount": 30,
    "cueCount": 61,
    "phraseCount": 105,
    "title": "2024 年 6 月四级阅读第 1 套"
  },
  {
    "id": "2023-12-3",
    "label": "2023 年 12 月 · 第 3 套",
    "year": 2023,
    "month": 12,
    "set": 3,
    "file": "./reading-data/2023-12-3.js",
    "pieceCount": 4,
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 31,
    "questionCount": 30,
    "cueCount": 50,
    "phraseCount": 124,
    "title": "2023 年 12 月四级阅读第 3 套"
  },
  {
    "id": "2023-12-2",
    "label": "2023 年 12 月 · 第 2 套",
    "year": 2023,
    "month": 12,
    "set": 2,
    "file": "./reading-data/2023-12-2.js",
    "pieceCount": 4,
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 28,
    "questionCount": 30,
    "cueCount": 61,
    "phraseCount": 112,
    "title": "2023 年 12 月四级阅读第 2 套"
  },
  {
    "id": "2023-12-1",
    "label": "2023 年 12 月 · 第 1 套",
    "year": 2023,
    "month": 12,
    "set": 1,
    "file": "./reading-data/2023-12-1.js",
    "pieceCount": 4,
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 29,
    "questionCount": 30,
    "cueCount": 63,
    "phraseCount": 113,
    "title": "2023 年 12 月四级阅读第 1 套"
  },
  {
    "id": "2023-06-3",
    "label": "2023 年 6 月 · 第 3 套",
    "year": 2023,
    "month": 6,
    "set": 3,
    "file": "./reading-data/2023-06-3.js",
    "pieceCount": 4,
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 28,
    "questionCount": 30,
    "cueCount": 47,
    "phraseCount": 112,
    "title": "2023 年 6 月四级阅读第 3 套"
  },
  {
    "id": "2023-06-2",
    "label": "2023 年 6 月 · 第 2 套",
    "year": 2023,
    "month": 6,
    "set": 2,
    "file": "./reading-data/2023-06-2.js",
    "pieceCount": 4,
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 30,
    "questionCount": 30,
    "cueCount": 33,
    "phraseCount": 120,
    "title": "2023 年 6 月四级阅读第 2 套"
  },
  {
    "id": "2023-06-1",
    "label": "2023 年 6 月 · 第 1 套",
    "year": 2023,
    "month": 6,
    "set": 1,
    "file": "./reading-data/2023-06-1.js",
    "pieceCount": 4,
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 29,
    "questionCount": 30,
    "cueCount": 51,
    "phraseCount": 114,
    "title": "2023 年 6 月四级阅读第 1 套"
  },
  {
    "id": "2023-03-1",
    "label": "2023 年 3 月 · 第 1 套",
    "year": 2023,
    "month": 3,
    "set": 1,
    "file": "./reading-data/2023-03-1.js",
    "pieceCount": 4,
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 33,
    "questionCount": 30,
    "cueCount": 41,
    "phraseCount": 120,
    "title": "2023 年 3 月四级阅读第 1 套"
  },
  {
    "id": "2022-12-3",
    "label": "2022 年 12 月 · 第 3 套",
    "year": 2022,
    "month": 12,
    "set": 3,
    "file": "./reading-data/2022-12-3.js",
    "pieceCount": 4,
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 33,
    "questionCount": 30,
    "cueCount": 58,
    "phraseCount": 132,
    "title": "2022 年 12 月四级阅读第 3 套"
  },
  {
    "id": "2022-12-2",
    "label": "2022 年 12 月 · 第 2 套",
    "year": 2022,
    "month": 12,
    "set": 2,
    "file": "./reading-data/2022-12-2.js",
    "pieceCount": 4,
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 26,
    "questionCount": 30,
    "cueCount": 52,
    "phraseCount": 101,
    "title": "2022 年 12 月四级阅读第 2 套"
  },
  {
    "id": "2022-12-1",
    "label": "2022 年 12 月 · 第 1 套",
    "year": 2022,
    "month": 12,
    "set": 1,
    "file": "./reading-data/2022-12-1.js",
    "pieceCount": 4,
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 29,
    "questionCount": 30,
    "cueCount": 48,
    "phraseCount": 115,
    "title": "2022 年 12 月四级阅读第 1 套"
  },
  {
    "id": "2022-09-1",
    "label": "2022 年 9 月 · 第 1 套",
    "year": 2022,
    "month": 9,
    "set": 1,
    "file": "./reading-data/2022-09-1.js",
    "pieceCount": 4,
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 28,
    "questionCount": 30,
    "cueCount": 41,
    "phraseCount": 112,
    "title": "2022 年 9 月四级阅读第 1 套"
  },
  {
    "id": "2022-06-2",
    "label": "2022 年 6 月 · 第 2 套",
    "year": 2022,
    "month": 6,
    "set": 2,
    "file": "./reading-data/2022-06-2.js",
    "pieceCount": 4,
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 25,
    "questionCount": 30,
    "cueCount": 51,
    "phraseCount": 97,
    "title": "2022 年 6 月四级阅读第 2 套"
  },
  {
    "id": "2022-06-1",
    "label": "2022 年 6 月 · 第 1 套",
    "year": 2022,
    "month": 6,
    "set": 1,
    "file": "./reading-data/2022-06-1.js",
    "pieceCount": 4,
    "types": [
      {
        "kind": "cloze",
        "index": 1,
        "label": "选词填空",
        "range": "第 26–35 题"
      },
      {
        "kind": "matching",
        "index": 1,
        "label": "段落匹配",
        "range": "第 36–45 题"
      },
      {
        "kind": "careful",
        "index": 1,
        "label": "仔细阅读 1",
        "range": "第 46–50 题"
      },
      {
        "kind": "careful",
        "index": 2,
        "label": "仔细阅读 2",
        "range": "第 51–55 题"
      }
    ],
    "paragraphCount": 30,
    "questionCount": 30,
    "cueCount": 54,
    "phraseCount": 120,
    "title": "2022 年 6 月四级阅读第 1 套"
  }
];
