// Generated by scripts/build-kaoyan-library.mjs
window.IBALL_KAOYAN_INDEX = {
  "generatedAt": "2026-09-24",
  "source": "kaoyan-english 真题语料",
  "tracks": [
    {
      "id": "english-i",
      "label": "英语一",
      "short": "英一"
    },
    {
      "id": "english-ii",
      "label": "英语二",
      "short": "英二"
    }
  ],
  "papers": [
    {
      "id": "english-i-2026",
      "track": "english-i",
      "trackLabel": "英语一",
      "trackShort": "英一",
      "year": 2026,
      "label": "2026 考研英语一",
      "file": "./kaoyan-data/english-i-2026.js",
      "stats": {
        "sections": 8,
        "paragraphs": 27,
        "questions": 50,
        "words": 2696,
        "enrichment": 23
      },
      "sections": [
        {
          "id": "english-i-2026-reading-text-1",
          "section": "reading-text-1",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 1",
          "shortLabel": "T1",
          "paragraphs": 6,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2026-reading-text-2",
          "section": "reading-text-2",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 2",
          "shortLabel": "T2",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2026-reading-text-3",
          "section": "reading-text-3",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 3",
          "shortLabel": "T3",
          "paragraphs": 3,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2026-reading-text-4",
          "section": "reading-text-4",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 4",
          "shortLabel": "T4",
          "paragraphs": 4,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2026-cloze",
          "section": "cloze",
          "kind": "cloze",
          "kindLabel": "完形",
          "label": "完形填空",
          "shortLabel": "完形",
          "paragraphs": 3,
          "questions": 20,
          "enrichment": 14
        },
        {
          "id": "english-i-2026-new-question-type",
          "section": "new-question-type",
          "kind": "new-question-type",
          "kindLabel": "新题型",
          "label": "新题型",
          "shortLabel": "新题型",
          "paragraphs": 3,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2026-translation",
          "section": "translation",
          "kind": "translation",
          "kindLabel": "翻译",
          "label": "翻译",
          "shortLabel": "翻译",
          "paragraphs": 3,
          "questions": 5,
          "enrichment": 9
        },
        {
          "id": "english-i-2026-writing",
          "section": "writing",
          "kind": "writing",
          "kindLabel": "写作",
          "label": "写作",
          "shortLabel": "写作",
          "paragraphs": 0,
          "questions": 0,
          "enrichment": 0
        }
      ]
    },
    {
      "id": "english-i-2025",
      "track": "english-i",
      "trackLabel": "英语一",
      "trackShort": "英一",
      "year": 2025,
      "label": "2025 考研英语一",
      "file": "./kaoyan-data/english-i-2025.js",
      "stats": {
        "sections": 8,
        "paragraphs": 28,
        "questions": 49,
        "words": 2789,
        "enrichment": 23
      },
      "sections": [
        {
          "id": "english-i-2025-reading-text-1",
          "section": "reading-text-1",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 1",
          "shortLabel": "T1",
          "paragraphs": 4,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2025-reading-text-2",
          "section": "reading-text-2",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 2",
          "shortLabel": "T2",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2025-reading-text-3",
          "section": "reading-text-3",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 3",
          "shortLabel": "T3",
          "paragraphs": 4,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2025-reading-text-4",
          "section": "reading-text-4",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 4",
          "shortLabel": "T4",
          "paragraphs": 4,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2025-cloze",
          "section": "cloze",
          "kind": "cloze",
          "kindLabel": "完形",
          "label": "完形填空",
          "shortLabel": "完形",
          "paragraphs": 3,
          "questions": 20,
          "enrichment": 14
        },
        {
          "id": "english-i-2025-new-question-type",
          "section": "new-question-type",
          "kind": "new-question-type",
          "kindLabel": "新题型",
          "label": "新题型",
          "shortLabel": "新题型",
          "paragraphs": 4,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2025-translation",
          "section": "translation",
          "kind": "translation",
          "kindLabel": "翻译",
          "label": "翻译",
          "shortLabel": "翻译",
          "paragraphs": 4,
          "questions": 4,
          "enrichment": 9
        },
        {
          "id": "english-i-2025-writing",
          "section": "writing",
          "kind": "writing",
          "kindLabel": "写作",
          "label": "写作",
          "shortLabel": "写作",
          "paragraphs": 0,
          "questions": 0,
          "enrichment": 0
        }
      ]
    },
    {
      "id": "english-i-2024",
      "track": "english-i",
      "trackLabel": "英语一",
      "trackShort": "英一",
      "year": 2024,
      "label": "2024 考研英语一",
      "file": "./kaoyan-data/english-i-2024.js",
      "stats": {
        "sections": 8,
        "paragraphs": 39,
        "questions": 50,
        "words": 3296,
        "enrichment": 23
      },
      "sections": [
        {
          "id": "english-i-2024-reading-text-1",
          "section": "reading-text-1",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 1",
          "shortLabel": "T1",
          "paragraphs": 6,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2024-reading-text-2",
          "section": "reading-text-2",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 2",
          "shortLabel": "T2",
          "paragraphs": 6,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2024-reading-text-3",
          "section": "reading-text-3",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 3",
          "shortLabel": "T3",
          "paragraphs": 6,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2024-reading-text-4",
          "section": "reading-text-4",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 4",
          "shortLabel": "T4",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2024-cloze",
          "section": "cloze",
          "kind": "cloze",
          "kindLabel": "完形",
          "label": "完形填空",
          "shortLabel": "完形",
          "paragraphs": 5,
          "questions": 20,
          "enrichment": 14
        },
        {
          "id": "english-i-2024-new-question-type",
          "section": "new-question-type",
          "kind": "new-question-type",
          "kindLabel": "新题型",
          "label": "新题型",
          "shortLabel": "新题型",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2024-translation",
          "section": "translation",
          "kind": "translation",
          "kindLabel": "翻译",
          "label": "翻译",
          "shortLabel": "翻译",
          "paragraphs": 6,
          "questions": 5,
          "enrichment": 9
        },
        {
          "id": "english-i-2024-writing",
          "section": "writing",
          "kind": "writing",
          "kindLabel": "写作",
          "label": "写作",
          "shortLabel": "写作",
          "paragraphs": 0,
          "questions": 0,
          "enrichment": 0
        }
      ]
    },
    {
      "id": "english-i-2023",
      "track": "english-i",
      "trackLabel": "英语一",
      "trackShort": "英一",
      "year": 2023,
      "label": "2023 考研英语一",
      "file": "./kaoyan-data/english-i-2023.js",
      "stats": {
        "sections": 8,
        "paragraphs": 21,
        "questions": 50,
        "words": 2615,
        "enrichment": 23
      },
      "sections": [
        {
          "id": "english-i-2023-reading-text-1",
          "section": "reading-text-1",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 1",
          "shortLabel": "T1",
          "paragraphs": 3,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2023-reading-text-2",
          "section": "reading-text-2",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 2",
          "shortLabel": "T2",
          "paragraphs": 4,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2023-reading-text-3",
          "section": "reading-text-3",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 3",
          "shortLabel": "T3",
          "paragraphs": 3,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2023-reading-text-4",
          "section": "reading-text-4",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 4",
          "shortLabel": "T4",
          "paragraphs": 3,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2023-cloze",
          "section": "cloze",
          "kind": "cloze",
          "kindLabel": "完形",
          "label": "完形填空",
          "shortLabel": "完形",
          "paragraphs": 4,
          "questions": 20,
          "enrichment": 14
        },
        {
          "id": "english-i-2023-new-question-type",
          "section": "new-question-type",
          "kind": "new-question-type",
          "kindLabel": "新题型",
          "label": "新题型",
          "shortLabel": "新题型",
          "paragraphs": 1,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2023-translation",
          "section": "translation",
          "kind": "translation",
          "kindLabel": "翻译",
          "label": "翻译",
          "shortLabel": "翻译",
          "paragraphs": 3,
          "questions": 5,
          "enrichment": 9
        },
        {
          "id": "english-i-2023-writing",
          "section": "writing",
          "kind": "writing",
          "kindLabel": "写作",
          "label": "写作",
          "shortLabel": "写作",
          "paragraphs": 0,
          "questions": 0,
          "enrichment": 0
        }
      ]
    },
    {
      "id": "english-i-2022",
      "track": "english-i",
      "trackLabel": "英语一",
      "trackShort": "英一",
      "year": 2022,
      "label": "2022 考研英语一",
      "file": "./kaoyan-data/english-i-2022.js",
      "stats": {
        "sections": 8,
        "paragraphs": 32,
        "questions": 50,
        "words": 3297,
        "enrichment": 23
      },
      "sections": [
        {
          "id": "english-i-2022-reading-text-1",
          "section": "reading-text-1",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 1",
          "shortLabel": "T1",
          "paragraphs": 6,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2022-reading-text-2",
          "section": "reading-text-2",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 2",
          "shortLabel": "T2",
          "paragraphs": 3,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2022-reading-text-3",
          "section": "reading-text-3",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 3",
          "shortLabel": "T3",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2022-reading-text-4",
          "section": "reading-text-4",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 4",
          "shortLabel": "T4",
          "paragraphs": 6,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2022-cloze",
          "section": "cloze",
          "kind": "cloze",
          "kindLabel": "完形",
          "label": "完形填空",
          "shortLabel": "完形",
          "paragraphs": 3,
          "questions": 20,
          "enrichment": 14
        },
        {
          "id": "english-i-2022-new-question-type",
          "section": "new-question-type",
          "kind": "new-question-type",
          "kindLabel": "新题型",
          "label": "新题型",
          "shortLabel": "新题型",
          "paragraphs": 6,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2022-translation",
          "section": "translation",
          "kind": "translation",
          "kindLabel": "翻译",
          "label": "翻译",
          "shortLabel": "翻译",
          "paragraphs": 3,
          "questions": 5,
          "enrichment": 9
        },
        {
          "id": "english-i-2022-writing",
          "section": "writing",
          "kind": "writing",
          "kindLabel": "写作",
          "label": "写作",
          "shortLabel": "写作",
          "paragraphs": 0,
          "questions": 0,
          "enrichment": 0
        }
      ]
    },
    {
      "id": "english-i-2021",
      "track": "english-i",
      "trackLabel": "英语一",
      "trackShort": "英一",
      "year": 2021,
      "label": "2021 考研英语一",
      "file": "./kaoyan-data/english-i-2021.js",
      "stats": {
        "sections": 8,
        "paragraphs": 27,
        "questions": 50,
        "words": 3098,
        "enrichment": 23
      },
      "sections": [
        {
          "id": "english-i-2021-reading-text-1",
          "section": "reading-text-1",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 1",
          "shortLabel": "T1",
          "paragraphs": 3,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2021-reading-text-2",
          "section": "reading-text-2",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 2",
          "shortLabel": "T2",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2021-reading-text-3",
          "section": "reading-text-3",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 3",
          "shortLabel": "T3",
          "paragraphs": 4,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2021-reading-text-4",
          "section": "reading-text-4",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 4",
          "shortLabel": "T4",
          "paragraphs": 3,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2021-cloze",
          "section": "cloze",
          "kind": "cloze",
          "kindLabel": "完形",
          "label": "完形填空",
          "shortLabel": "完形",
          "paragraphs": 3,
          "questions": 20,
          "enrichment": 14
        },
        {
          "id": "english-i-2021-new-question-type",
          "section": "new-question-type",
          "kind": "new-question-type",
          "kindLabel": "新题型",
          "label": "新题型",
          "shortLabel": "新题型",
          "paragraphs": 4,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2021-translation",
          "section": "translation",
          "kind": "translation",
          "kindLabel": "翻译",
          "label": "翻译",
          "shortLabel": "翻译",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 9
        },
        {
          "id": "english-i-2021-writing",
          "section": "writing",
          "kind": "writing",
          "kindLabel": "写作",
          "label": "写作",
          "shortLabel": "写作",
          "paragraphs": 0,
          "questions": 0,
          "enrichment": 0
        }
      ]
    },
    {
      "id": "english-i-2020",
      "track": "english-i",
      "trackLabel": "英语一",
      "trackShort": "英一",
      "year": 2020,
      "label": "2020 考研英语一",
      "file": "./kaoyan-data/english-i-2020.js",
      "stats": {
        "sections": 8,
        "paragraphs": 35,
        "questions": 50,
        "words": 3413,
        "enrichment": 23
      },
      "sections": [
        {
          "id": "english-i-2020-reading-text-1",
          "section": "reading-text-1",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 1",
          "shortLabel": "T1",
          "paragraphs": 4,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2020-reading-text-2",
          "section": "reading-text-2",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 2",
          "shortLabel": "T2",
          "paragraphs": 4,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2020-reading-text-3",
          "section": "reading-text-3",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 3",
          "shortLabel": "T3",
          "paragraphs": 7,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2020-reading-text-4",
          "section": "reading-text-4",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 4",
          "shortLabel": "T4",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2020-cloze",
          "section": "cloze",
          "kind": "cloze",
          "kindLabel": "完形",
          "label": "完形填空",
          "shortLabel": "完形",
          "paragraphs": 3,
          "questions": 20,
          "enrichment": 14
        },
        {
          "id": "english-i-2020-new-question-type",
          "section": "new-question-type",
          "kind": "new-question-type",
          "kindLabel": "新题型",
          "label": "新题型",
          "shortLabel": "新题型",
          "paragraphs": 8,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2020-translation",
          "section": "translation",
          "kind": "translation",
          "kindLabel": "翻译",
          "label": "翻译",
          "shortLabel": "翻译",
          "paragraphs": 4,
          "questions": 5,
          "enrichment": 9
        },
        {
          "id": "english-i-2020-writing",
          "section": "writing",
          "kind": "writing",
          "kindLabel": "写作",
          "label": "写作",
          "shortLabel": "写作",
          "paragraphs": 0,
          "questions": 0,
          "enrichment": 0
        }
      ]
    },
    {
      "id": "english-i-2019",
      "track": "english-i",
      "trackLabel": "英语一",
      "trackShort": "英一",
      "year": 2019,
      "label": "2019 考研英语一",
      "file": "./kaoyan-data/english-i-2019.js",
      "stats": {
        "sections": 8,
        "paragraphs": 31,
        "questions": 50,
        "words": 2642,
        "enrichment": 23
      },
      "sections": [
        {
          "id": "english-i-2019-reading-text-1",
          "section": "reading-text-1",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 1",
          "shortLabel": "T1",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2019-reading-text-2",
          "section": "reading-text-2",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 2",
          "shortLabel": "T2",
          "paragraphs": 4,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2019-reading-text-3",
          "section": "reading-text-3",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 3",
          "shortLabel": "T3",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2019-reading-text-4",
          "section": "reading-text-4",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 4",
          "shortLabel": "T4",
          "paragraphs": 7,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2019-cloze",
          "section": "cloze",
          "kind": "cloze",
          "kindLabel": "完形",
          "label": "完形填空",
          "shortLabel": "完形",
          "paragraphs": 4,
          "questions": 20,
          "enrichment": 14
        },
        {
          "id": "english-i-2019-new-question-type",
          "section": "new-question-type",
          "kind": "new-question-type",
          "kindLabel": "新题型",
          "label": "新题型",
          "shortLabel": "新题型",
          "paragraphs": 1,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2019-translation",
          "section": "translation",
          "kind": "translation",
          "kindLabel": "翻译",
          "label": "翻译",
          "shortLabel": "翻译",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 9
        },
        {
          "id": "english-i-2019-writing",
          "section": "writing",
          "kind": "writing",
          "kindLabel": "写作",
          "label": "写作",
          "shortLabel": "写作",
          "paragraphs": 0,
          "questions": 0,
          "enrichment": 0
        }
      ]
    },
    {
      "id": "english-i-2018",
      "track": "english-i",
      "trackLabel": "英语一",
      "trackShort": "英一",
      "year": 2018,
      "label": "2018 考研英语一",
      "file": "./kaoyan-data/english-i-2018.js",
      "stats": {
        "sections": 8,
        "paragraphs": 27,
        "questions": 50,
        "words": 2656,
        "enrichment": 23
      },
      "sections": [
        {
          "id": "english-i-2018-reading-text-1",
          "section": "reading-text-1",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 1",
          "shortLabel": "T1",
          "paragraphs": 6,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2018-reading-text-2",
          "section": "reading-text-2",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 2",
          "shortLabel": "T2",
          "paragraphs": 6,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2018-reading-text-3",
          "section": "reading-text-3",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 3",
          "shortLabel": "T3",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2018-reading-text-4",
          "section": "reading-text-4",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 4",
          "shortLabel": "T4",
          "paragraphs": 3,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2018-cloze",
          "section": "cloze",
          "kind": "cloze",
          "kindLabel": "完形",
          "label": "完形填空",
          "shortLabel": "完形",
          "paragraphs": 3,
          "questions": 20,
          "enrichment": 14
        },
        {
          "id": "english-i-2018-new-question-type",
          "section": "new-question-type",
          "kind": "new-question-type",
          "kindLabel": "新题型",
          "label": "新题型",
          "shortLabel": "新题型",
          "paragraphs": 1,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2018-translation",
          "section": "translation",
          "kind": "translation",
          "kindLabel": "翻译",
          "label": "翻译",
          "shortLabel": "翻译",
          "paragraphs": 3,
          "questions": 5,
          "enrichment": 9
        },
        {
          "id": "english-i-2018-writing",
          "section": "writing",
          "kind": "writing",
          "kindLabel": "写作",
          "label": "写作",
          "shortLabel": "写作",
          "paragraphs": 0,
          "questions": 0,
          "enrichment": 0
        }
      ]
    },
    {
      "id": "english-i-2017",
      "track": "english-i",
      "trackLabel": "英语一",
      "trackShort": "英一",
      "year": 2017,
      "label": "2017 考研英语一",
      "file": "./kaoyan-data/english-i-2017.js",
      "stats": {
        "sections": 8,
        "paragraphs": 35,
        "questions": 50,
        "words": 2701,
        "enrichment": 23
      },
      "sections": [
        {
          "id": "english-i-2017-reading-text-1",
          "section": "reading-text-1",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 1",
          "shortLabel": "T1",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2017-reading-text-2",
          "section": "reading-text-2",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 2",
          "shortLabel": "T2",
          "paragraphs": 4,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2017-reading-text-3",
          "section": "reading-text-3",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 3",
          "shortLabel": "T3",
          "paragraphs": 8,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2017-reading-text-4",
          "section": "reading-text-4",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 4",
          "shortLabel": "T4",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2017-cloze",
          "section": "cloze",
          "kind": "cloze",
          "kindLabel": "完形",
          "label": "完形填空",
          "shortLabel": "完形",
          "paragraphs": 3,
          "questions": 20,
          "enrichment": 14
        },
        {
          "id": "english-i-2017-new-question-type",
          "section": "new-question-type",
          "kind": "new-question-type",
          "kindLabel": "新题型",
          "label": "新题型",
          "shortLabel": "新题型",
          "paragraphs": 4,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2017-translation",
          "section": "translation",
          "kind": "translation",
          "kindLabel": "翻译",
          "label": "翻译",
          "shortLabel": "翻译",
          "paragraphs": 6,
          "questions": 5,
          "enrichment": 9
        },
        {
          "id": "english-i-2017-writing",
          "section": "writing",
          "kind": "writing",
          "kindLabel": "写作",
          "label": "写作",
          "shortLabel": "写作",
          "paragraphs": 0,
          "questions": 0,
          "enrichment": 0
        }
      ]
    },
    {
      "id": "english-i-2016",
      "track": "english-i",
      "trackLabel": "英语一",
      "trackShort": "英一",
      "year": 2016,
      "label": "2016 考研英语一",
      "file": "./kaoyan-data/english-i-2016.js",
      "stats": {
        "sections": 8,
        "paragraphs": 32,
        "questions": 50,
        "words": 3490,
        "enrichment": 23
      },
      "sections": [
        {
          "id": "english-i-2016-reading-text-1",
          "section": "reading-text-1",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 1",
          "shortLabel": "T1",
          "paragraphs": 3,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2016-reading-text-2",
          "section": "reading-text-2",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 2",
          "shortLabel": "T2",
          "paragraphs": 4,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2016-reading-text-3",
          "section": "reading-text-3",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 3",
          "shortLabel": "T3",
          "paragraphs": 4,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2016-reading-text-4",
          "section": "reading-text-4",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 4",
          "shortLabel": "T4",
          "paragraphs": 3,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2016-cloze",
          "section": "cloze",
          "kind": "cloze",
          "kindLabel": "完形",
          "label": "完形填空",
          "shortLabel": "完形",
          "paragraphs": 4,
          "questions": 20,
          "enrichment": 14
        },
        {
          "id": "english-i-2016-new-question-type",
          "section": "new-question-type",
          "kind": "new-question-type",
          "kindLabel": "新题型",
          "label": "新题型",
          "shortLabel": "新题型",
          "paragraphs": 11,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2016-translation",
          "section": "translation",
          "kind": "translation",
          "kindLabel": "翻译",
          "label": "翻译",
          "shortLabel": "翻译",
          "paragraphs": 3,
          "questions": 5,
          "enrichment": 9
        },
        {
          "id": "english-i-2016-writing",
          "section": "writing",
          "kind": "writing",
          "kindLabel": "写作",
          "label": "写作",
          "shortLabel": "写作",
          "paragraphs": 0,
          "questions": 0,
          "enrichment": 0
        }
      ]
    },
    {
      "id": "english-i-2015",
      "track": "english-i",
      "trackLabel": "英语一",
      "trackShort": "英一",
      "year": 2015,
      "label": "2015 考研英语一",
      "file": "./kaoyan-data/english-i-2015.js",
      "stats": {
        "sections": 8,
        "paragraphs": 32,
        "questions": 50,
        "words": 3068,
        "enrichment": 23
      },
      "sections": [
        {
          "id": "english-i-2015-reading-text-1",
          "section": "reading-text-1",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 1",
          "shortLabel": "T1",
          "paragraphs": 6,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2015-reading-text-2",
          "section": "reading-text-2",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 2",
          "shortLabel": "T2",
          "paragraphs": 4,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2015-reading-text-3",
          "section": "reading-text-3",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 3",
          "shortLabel": "T3",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2015-reading-text-4",
          "section": "reading-text-4",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 4",
          "shortLabel": "T4",
          "paragraphs": 3,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2015-cloze",
          "section": "cloze",
          "kind": "cloze",
          "kindLabel": "完形",
          "label": "完形填空",
          "shortLabel": "完形",
          "paragraphs": 6,
          "questions": 20,
          "enrichment": 14
        },
        {
          "id": "english-i-2015-new-question-type",
          "section": "new-question-type",
          "kind": "new-question-type",
          "kindLabel": "新题型",
          "label": "新题型",
          "shortLabel": "新题型",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2015-translation",
          "section": "translation",
          "kind": "translation",
          "kindLabel": "翻译",
          "label": "翻译",
          "shortLabel": "翻译",
          "paragraphs": 3,
          "questions": 5,
          "enrichment": 9
        },
        {
          "id": "english-i-2015-writing",
          "section": "writing",
          "kind": "writing",
          "kindLabel": "写作",
          "label": "写作",
          "shortLabel": "写作",
          "paragraphs": 0,
          "questions": 0,
          "enrichment": 0
        }
      ]
    },
    {
      "id": "english-i-2014",
      "track": "english-i",
      "trackLabel": "英语一",
      "trackShort": "英一",
      "year": 2014,
      "label": "2014 考研英语一",
      "file": "./kaoyan-data/english-i-2014.js",
      "stats": {
        "sections": 8,
        "paragraphs": 29,
        "questions": 50,
        "words": 2714,
        "enrichment": 23
      },
      "sections": [
        {
          "id": "english-i-2014-reading-text-1",
          "section": "reading-text-1",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 1",
          "shortLabel": "T1",
          "paragraphs": 4,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2014-reading-text-2",
          "section": "reading-text-2",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 2",
          "shortLabel": "T2",
          "paragraphs": 3,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2014-reading-text-3",
          "section": "reading-text-3",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 3",
          "shortLabel": "T3",
          "paragraphs": 7,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2014-reading-text-4",
          "section": "reading-text-4",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 4",
          "shortLabel": "T4",
          "paragraphs": 6,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2014-cloze",
          "section": "cloze",
          "kind": "cloze",
          "kindLabel": "完形",
          "label": "完形填空",
          "shortLabel": "完形",
          "paragraphs": 3,
          "questions": 20,
          "enrichment": 14
        },
        {
          "id": "english-i-2014-new-question-type",
          "section": "new-question-type",
          "kind": "new-question-type",
          "kindLabel": "新题型",
          "label": "新题型",
          "shortLabel": "新题型",
          "paragraphs": 2,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2014-translation",
          "section": "translation",
          "kind": "translation",
          "kindLabel": "翻译",
          "label": "翻译",
          "shortLabel": "翻译",
          "paragraphs": 4,
          "questions": 5,
          "enrichment": 9
        },
        {
          "id": "english-i-2014-writing",
          "section": "writing",
          "kind": "writing",
          "kindLabel": "写作",
          "label": "写作",
          "shortLabel": "写作",
          "paragraphs": 0,
          "questions": 0,
          "enrichment": 0
        }
      ]
    },
    {
      "id": "english-i-2013",
      "track": "english-i",
      "trackLabel": "英语一",
      "trackShort": "英一",
      "year": 2013,
      "label": "2013 考研英语一",
      "file": "./kaoyan-data/english-i-2013.js",
      "stats": {
        "sections": 8,
        "paragraphs": 28,
        "questions": 50,
        "words": 3082,
        "enrichment": 23
      },
      "sections": [
        {
          "id": "english-i-2013-reading-text-1",
          "section": "reading-text-1",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 1",
          "shortLabel": "T1",
          "paragraphs": 3,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2013-reading-text-2",
          "section": "reading-text-2",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 2",
          "shortLabel": "T2",
          "paragraphs": 3,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2013-reading-text-3",
          "section": "reading-text-3",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 3",
          "shortLabel": "T3",
          "paragraphs": 4,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2013-reading-text-4",
          "section": "reading-text-4",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 4",
          "shortLabel": "T4",
          "paragraphs": 6,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2013-cloze",
          "section": "cloze",
          "kind": "cloze",
          "kindLabel": "完形",
          "label": "完形填空",
          "shortLabel": "完形",
          "paragraphs": 3,
          "questions": 20,
          "enrichment": 14
        },
        {
          "id": "english-i-2013-new-question-type",
          "section": "new-question-type",
          "kind": "new-question-type",
          "kindLabel": "新题型",
          "label": "新题型",
          "shortLabel": "新题型",
          "paragraphs": 6,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2013-translation",
          "section": "translation",
          "kind": "translation",
          "kindLabel": "翻译",
          "label": "翻译",
          "shortLabel": "翻译",
          "paragraphs": 3,
          "questions": 5,
          "enrichment": 9
        },
        {
          "id": "english-i-2013-writing",
          "section": "writing",
          "kind": "writing",
          "kindLabel": "写作",
          "label": "写作",
          "shortLabel": "写作",
          "paragraphs": 0,
          "questions": 0,
          "enrichment": 0
        }
      ]
    },
    {
      "id": "english-i-2012",
      "track": "english-i",
      "trackLabel": "英语一",
      "trackShort": "英一",
      "year": 2012,
      "label": "2012 考研英语一",
      "file": "./kaoyan-data/english-i-2012.js",
      "stats": {
        "sections": 8,
        "paragraphs": 34,
        "questions": 50,
        "words": 3141,
        "enrichment": 23
      },
      "sections": [
        {
          "id": "english-i-2012-reading-text-1",
          "section": "reading-text-1",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 1",
          "shortLabel": "T1",
          "paragraphs": 3,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2012-reading-text-2",
          "section": "reading-text-2",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 2",
          "shortLabel": "T2",
          "paragraphs": 6,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2012-reading-text-3",
          "section": "reading-text-3",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 3",
          "shortLabel": "T3",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2012-reading-text-4",
          "section": "reading-text-4",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 4",
          "shortLabel": "T4",
          "paragraphs": 6,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2012-cloze",
          "section": "cloze",
          "kind": "cloze",
          "kindLabel": "完形",
          "label": "完形填空",
          "shortLabel": "完形",
          "paragraphs": 5,
          "questions": 20,
          "enrichment": 14
        },
        {
          "id": "english-i-2012-new-question-type",
          "section": "new-question-type",
          "kind": "new-question-type",
          "kindLabel": "新题型",
          "label": "新题型",
          "shortLabel": "新题型",
          "paragraphs": 3,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2012-translation",
          "section": "translation",
          "kind": "translation",
          "kindLabel": "翻译",
          "label": "翻译",
          "shortLabel": "翻译",
          "paragraphs": 6,
          "questions": 5,
          "enrichment": 9
        },
        {
          "id": "english-i-2012-writing",
          "section": "writing",
          "kind": "writing",
          "kindLabel": "写作",
          "label": "写作",
          "shortLabel": "写作",
          "paragraphs": 0,
          "questions": 0,
          "enrichment": 0
        }
      ]
    },
    {
      "id": "english-i-2011",
      "track": "english-i",
      "trackLabel": "英语一",
      "trackShort": "英一",
      "year": 2011,
      "label": "2011 考研英语一",
      "file": "./kaoyan-data/english-i-2011.js",
      "stats": {
        "sections": 8,
        "paragraphs": 23,
        "questions": 50,
        "words": 2677,
        "enrichment": 23
      },
      "sections": [
        {
          "id": "english-i-2011-reading-text-1",
          "section": "reading-text-1",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 1",
          "shortLabel": "T1",
          "paragraphs": 3,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2011-reading-text-2",
          "section": "reading-text-2",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 2",
          "shortLabel": "T2",
          "paragraphs": 4,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2011-reading-text-3",
          "section": "reading-text-3",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 3",
          "shortLabel": "T3",
          "paragraphs": 4,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2011-reading-text-4",
          "section": "reading-text-4",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 4",
          "shortLabel": "T4",
          "paragraphs": 3,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2011-cloze",
          "section": "cloze",
          "kind": "cloze",
          "kindLabel": "完形",
          "label": "完形填空",
          "shortLabel": "完形",
          "paragraphs": 3,
          "questions": 20,
          "enrichment": 14
        },
        {
          "id": "english-i-2011-new-question-type",
          "section": "new-question-type",
          "kind": "new-question-type",
          "kindLabel": "新题型",
          "label": "新题型",
          "shortLabel": "新题型",
          "paragraphs": 1,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2011-translation",
          "section": "translation",
          "kind": "translation",
          "kindLabel": "翻译",
          "label": "翻译",
          "shortLabel": "翻译",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 9
        },
        {
          "id": "english-i-2011-writing",
          "section": "writing",
          "kind": "writing",
          "kindLabel": "写作",
          "label": "写作",
          "shortLabel": "写作",
          "paragraphs": 0,
          "questions": 0,
          "enrichment": 0
        }
      ]
    },
    {
      "id": "english-i-2010",
      "track": "english-i",
      "trackLabel": "英语一",
      "trackShort": "英一",
      "year": 2010,
      "label": "2010 考研英语一",
      "file": "./kaoyan-data/english-i-2010.js",
      "stats": {
        "sections": 8,
        "paragraphs": 25,
        "questions": 50,
        "words": 2780,
        "enrichment": 23
      },
      "sections": [
        {
          "id": "english-i-2010-reading-text-1",
          "section": "reading-text-1",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 1",
          "shortLabel": "T1",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2010-reading-text-2",
          "section": "reading-text-2",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 2",
          "shortLabel": "T2",
          "paragraphs": 4,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2010-reading-text-3",
          "section": "reading-text-3",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 3",
          "shortLabel": "T3",
          "paragraphs": 3,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2010-reading-text-4",
          "section": "reading-text-4",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 4",
          "shortLabel": "T4",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2010-cloze",
          "section": "cloze",
          "kind": "cloze",
          "kindLabel": "完形",
          "label": "完形填空",
          "shortLabel": "完形",
          "paragraphs": 3,
          "questions": 20,
          "enrichment": 14
        },
        {
          "id": "english-i-2010-new-question-type",
          "section": "new-question-type",
          "kind": "new-question-type",
          "kindLabel": "新题型",
          "label": "新题型",
          "shortLabel": "新题型",
          "paragraphs": 2,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-i-2010-translation",
          "section": "translation",
          "kind": "translation",
          "kindLabel": "翻译",
          "label": "翻译",
          "shortLabel": "翻译",
          "paragraphs": 3,
          "questions": 5,
          "enrichment": 9
        },
        {
          "id": "english-i-2010-writing",
          "section": "writing",
          "kind": "writing",
          "kindLabel": "写作",
          "label": "写作",
          "shortLabel": "写作",
          "paragraphs": 0,
          "questions": 0,
          "enrichment": 0
        }
      ]
    },
    {
      "id": "english-ii-2026",
      "track": "english-ii",
      "trackLabel": "英语二",
      "trackShort": "英二",
      "year": 2026,
      "label": "2026 考研英语二",
      "file": "./kaoyan-data/english-ii-2026.js",
      "stats": {
        "sections": 8,
        "paragraphs": 31,
        "questions": 46,
        "words": 2904,
        "enrichment": 23
      },
      "sections": [
        {
          "id": "english-ii-2026-reading-text-1",
          "section": "reading-text-1",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 1",
          "shortLabel": "T1",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2026-reading-text-2",
          "section": "reading-text-2",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 2",
          "shortLabel": "T2",
          "paragraphs": 4,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2026-reading-text-3",
          "section": "reading-text-3",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 3",
          "shortLabel": "T3",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2026-reading-text-4",
          "section": "reading-text-4",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 4",
          "shortLabel": "T4",
          "paragraphs": 3,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2026-cloze",
          "section": "cloze",
          "kind": "cloze",
          "kindLabel": "完形",
          "label": "完形填空",
          "shortLabel": "完形",
          "paragraphs": 6,
          "questions": 20,
          "enrichment": 14
        },
        {
          "id": "english-ii-2026-new-question-type",
          "section": "new-question-type",
          "kind": "new-question-type",
          "kindLabel": "新题型",
          "label": "新题型",
          "shortLabel": "新题型",
          "paragraphs": 4,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2026-translation",
          "section": "translation",
          "kind": "translation",
          "kindLabel": "翻译",
          "label": "翻译",
          "shortLabel": "翻译",
          "paragraphs": 4,
          "questions": 1,
          "enrichment": 9
        },
        {
          "id": "english-ii-2026-writing",
          "section": "writing",
          "kind": "writing",
          "kindLabel": "写作",
          "label": "写作",
          "shortLabel": "写作",
          "paragraphs": 0,
          "questions": 0,
          "enrichment": 0
        }
      ]
    },
    {
      "id": "english-ii-2025",
      "track": "english-ii",
      "trackLabel": "英语二",
      "trackShort": "英二",
      "year": 2025,
      "label": "2025 考研英语二",
      "file": "./kaoyan-data/english-ii-2025.js",
      "stats": {
        "sections": 8,
        "paragraphs": 35,
        "questions": 45,
        "words": 3182,
        "enrichment": 23
      },
      "sections": [
        {
          "id": "english-ii-2025-reading-text-1",
          "section": "reading-text-1",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 1",
          "shortLabel": "T1",
          "paragraphs": 4,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2025-reading-text-2",
          "section": "reading-text-2",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 2",
          "shortLabel": "T2",
          "paragraphs": 4,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2025-reading-text-3",
          "section": "reading-text-3",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 3",
          "shortLabel": "T3",
          "paragraphs": 5,
          "questions": 4,
          "enrichment": 0
        },
        {
          "id": "english-ii-2025-reading-text-4",
          "section": "reading-text-4",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 4",
          "shortLabel": "T4",
          "paragraphs": 4,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2025-cloze",
          "section": "cloze",
          "kind": "cloze",
          "kindLabel": "完形",
          "label": "完形填空",
          "shortLabel": "完形",
          "paragraphs": 4,
          "questions": 20,
          "enrichment": 14
        },
        {
          "id": "english-ii-2025-new-question-type",
          "section": "new-question-type",
          "kind": "new-question-type",
          "kindLabel": "新题型",
          "label": "新题型",
          "shortLabel": "新题型",
          "paragraphs": 11,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2025-translation",
          "section": "translation",
          "kind": "translation",
          "kindLabel": "翻译",
          "label": "翻译",
          "shortLabel": "翻译",
          "paragraphs": 3,
          "questions": 1,
          "enrichment": 9
        },
        {
          "id": "english-ii-2025-writing",
          "section": "writing",
          "kind": "writing",
          "kindLabel": "写作",
          "label": "写作",
          "shortLabel": "写作",
          "paragraphs": 0,
          "questions": 0,
          "enrichment": 0
        }
      ]
    },
    {
      "id": "english-ii-2024",
      "track": "english-ii",
      "trackLabel": "英语二",
      "trackShort": "英二",
      "year": 2024,
      "label": "2024 考研英语二",
      "file": "./kaoyan-data/english-ii-2024.js",
      "stats": {
        "sections": 8,
        "paragraphs": 32,
        "questions": 46,
        "words": 2881,
        "enrichment": 23
      },
      "sections": [
        {
          "id": "english-ii-2024-reading-text-1",
          "section": "reading-text-1",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 1",
          "shortLabel": "T1",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2024-reading-text-2",
          "section": "reading-text-2",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 2",
          "shortLabel": "T2",
          "paragraphs": 4,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2024-reading-text-3",
          "section": "reading-text-3",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 3",
          "shortLabel": "T3",
          "paragraphs": 3,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2024-reading-text-4",
          "section": "reading-text-4",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 4",
          "shortLabel": "T4",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2024-cloze",
          "section": "cloze",
          "kind": "cloze",
          "kindLabel": "完形",
          "label": "完形填空",
          "shortLabel": "完形",
          "paragraphs": 3,
          "questions": 20,
          "enrichment": 14
        },
        {
          "id": "english-ii-2024-new-question-type",
          "section": "new-question-type",
          "kind": "new-question-type",
          "kindLabel": "新题型",
          "label": "新题型",
          "shortLabel": "新题型",
          "paragraphs": 10,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2024-translation",
          "section": "translation",
          "kind": "translation",
          "kindLabel": "翻译",
          "label": "翻译",
          "shortLabel": "翻译",
          "paragraphs": 2,
          "questions": 1,
          "enrichment": 9
        },
        {
          "id": "english-ii-2024-writing",
          "section": "writing",
          "kind": "writing",
          "kindLabel": "写作",
          "label": "写作",
          "shortLabel": "写作",
          "paragraphs": 0,
          "questions": 0,
          "enrichment": 0
        }
      ]
    },
    {
      "id": "english-ii-2023",
      "track": "english-ii",
      "trackLabel": "英语二",
      "trackShort": "英二",
      "year": 2023,
      "label": "2023 考研英语二",
      "file": "./kaoyan-data/english-ii-2023.js",
      "stats": {
        "sections": 8,
        "paragraphs": 28,
        "questions": 46,
        "words": 2889,
        "enrichment": 23
      },
      "sections": [
        {
          "id": "english-ii-2023-reading-text-1",
          "section": "reading-text-1",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 1",
          "shortLabel": "T1",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2023-reading-text-2",
          "section": "reading-text-2",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 2",
          "shortLabel": "T2",
          "paragraphs": 4,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2023-reading-text-3",
          "section": "reading-text-3",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 3",
          "shortLabel": "T3",
          "paragraphs": 4,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2023-reading-text-4",
          "section": "reading-text-4",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 4",
          "shortLabel": "T4",
          "paragraphs": 4,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2023-cloze",
          "section": "cloze",
          "kind": "cloze",
          "kindLabel": "完形",
          "label": "完形填空",
          "shortLabel": "完形",
          "paragraphs": 3,
          "questions": 20,
          "enrichment": 14
        },
        {
          "id": "english-ii-2023-new-question-type",
          "section": "new-question-type",
          "kind": "new-question-type",
          "kindLabel": "新题型",
          "label": "新题型",
          "shortLabel": "新题型",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2023-translation",
          "section": "translation",
          "kind": "translation",
          "kindLabel": "翻译",
          "label": "翻译",
          "shortLabel": "翻译",
          "paragraphs": 3,
          "questions": 1,
          "enrichment": 9
        },
        {
          "id": "english-ii-2023-writing",
          "section": "writing",
          "kind": "writing",
          "kindLabel": "写作",
          "label": "写作",
          "shortLabel": "写作",
          "paragraphs": 0,
          "questions": 0,
          "enrichment": 0
        }
      ]
    },
    {
      "id": "english-ii-2022",
      "track": "english-ii",
      "trackLabel": "英语二",
      "trackShort": "英二",
      "year": 2022,
      "label": "2022 考研英语二",
      "file": "./kaoyan-data/english-ii-2022.js",
      "stats": {
        "sections": 8,
        "paragraphs": 33,
        "questions": 46,
        "words": 3296,
        "enrichment": 23
      },
      "sections": [
        {
          "id": "english-ii-2022-reading-text-1",
          "section": "reading-text-1",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 1",
          "shortLabel": "T1",
          "paragraphs": 4,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2022-reading-text-2",
          "section": "reading-text-2",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 2",
          "shortLabel": "T2",
          "paragraphs": 6,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2022-reading-text-3",
          "section": "reading-text-3",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 3",
          "shortLabel": "T3",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2022-reading-text-4",
          "section": "reading-text-4",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 4",
          "shortLabel": "T4",
          "paragraphs": 4,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2022-cloze",
          "section": "cloze",
          "kind": "cloze",
          "kindLabel": "完形",
          "label": "完形填空",
          "shortLabel": "完形",
          "paragraphs": 5,
          "questions": 20,
          "enrichment": 14
        },
        {
          "id": "english-ii-2022-new-question-type",
          "section": "new-question-type",
          "kind": "new-question-type",
          "kindLabel": "新题型",
          "label": "新题型",
          "shortLabel": "新题型",
          "paragraphs": 6,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2022-translation",
          "section": "translation",
          "kind": "translation",
          "kindLabel": "翻译",
          "label": "翻译",
          "shortLabel": "翻译",
          "paragraphs": 3,
          "questions": 1,
          "enrichment": 9
        },
        {
          "id": "english-ii-2022-writing",
          "section": "writing",
          "kind": "writing",
          "kindLabel": "写作",
          "label": "写作",
          "shortLabel": "写作",
          "paragraphs": 0,
          "questions": 0,
          "enrichment": 0
        }
      ]
    },
    {
      "id": "english-ii-2021",
      "track": "english-ii",
      "trackLabel": "英语二",
      "trackShort": "英二",
      "year": 2021,
      "label": "2021 考研英语二",
      "file": "./kaoyan-data/english-ii-2021.js",
      "stats": {
        "sections": 8,
        "paragraphs": 34,
        "questions": 46,
        "words": 3347,
        "enrichment": 23
      },
      "sections": [
        {
          "id": "english-ii-2021-reading-text-1",
          "section": "reading-text-1",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 1",
          "shortLabel": "T1",
          "paragraphs": 6,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2021-reading-text-2",
          "section": "reading-text-2",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 2",
          "shortLabel": "T2",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2021-reading-text-3",
          "section": "reading-text-3",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 3",
          "shortLabel": "T3",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2021-reading-text-4",
          "section": "reading-text-4",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 4",
          "shortLabel": "T4",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2021-cloze",
          "section": "cloze",
          "kind": "cloze",
          "kindLabel": "完形",
          "label": "完形填空",
          "shortLabel": "完形",
          "paragraphs": 4,
          "questions": 20,
          "enrichment": 14
        },
        {
          "id": "english-ii-2021-new-question-type",
          "section": "new-question-type",
          "kind": "new-question-type",
          "kindLabel": "新题型",
          "label": "新题型",
          "shortLabel": "新题型",
          "paragraphs": 6,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2021-translation",
          "section": "translation",
          "kind": "translation",
          "kindLabel": "翻译",
          "label": "翻译",
          "shortLabel": "翻译",
          "paragraphs": 3,
          "questions": 1,
          "enrichment": 9
        },
        {
          "id": "english-ii-2021-writing",
          "section": "writing",
          "kind": "writing",
          "kindLabel": "写作",
          "label": "写作",
          "shortLabel": "写作",
          "paragraphs": 0,
          "questions": 0,
          "enrichment": 0
        }
      ]
    },
    {
      "id": "english-ii-2020",
      "track": "english-ii",
      "trackLabel": "英语二",
      "trackShort": "英二",
      "year": 2020,
      "label": "2020 考研英语二",
      "file": "./kaoyan-data/english-ii-2020.js",
      "stats": {
        "sections": 8,
        "paragraphs": 32,
        "questions": 46,
        "words": 3252,
        "enrichment": 23
      },
      "sections": [
        {
          "id": "english-ii-2020-reading-text-1",
          "section": "reading-text-1",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 1",
          "shortLabel": "T1",
          "paragraphs": 6,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2020-reading-text-2",
          "section": "reading-text-2",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 2",
          "shortLabel": "T2",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2020-reading-text-3",
          "section": "reading-text-3",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 3",
          "shortLabel": "T3",
          "paragraphs": 3,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2020-reading-text-4",
          "section": "reading-text-4",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 4",
          "shortLabel": "T4",
          "paragraphs": 3,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2020-cloze",
          "section": "cloze",
          "kind": "cloze",
          "kindLabel": "完形",
          "label": "完形填空",
          "shortLabel": "完形",
          "paragraphs": 7,
          "questions": 20,
          "enrichment": 14
        },
        {
          "id": "english-ii-2020-new-question-type",
          "section": "new-question-type",
          "kind": "new-question-type",
          "kindLabel": "新题型",
          "label": "新题型",
          "shortLabel": "新题型",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2020-translation",
          "section": "translation",
          "kind": "translation",
          "kindLabel": "翻译",
          "label": "翻译",
          "shortLabel": "翻译",
          "paragraphs": 3,
          "questions": 1,
          "enrichment": 9
        },
        {
          "id": "english-ii-2020-writing",
          "section": "writing",
          "kind": "writing",
          "kindLabel": "写作",
          "label": "写作",
          "shortLabel": "写作",
          "paragraphs": 0,
          "questions": 0,
          "enrichment": 0
        }
      ]
    },
    {
      "id": "english-ii-2019",
      "track": "english-ii",
      "trackLabel": "英语二",
      "trackShort": "英二",
      "year": 2019,
      "label": "2019 考研英语二",
      "file": "./kaoyan-data/english-ii-2019.js",
      "stats": {
        "sections": 8,
        "paragraphs": 36,
        "questions": 46,
        "words": 2929,
        "enrichment": 23
      },
      "sections": [
        {
          "id": "english-ii-2019-reading-text-1",
          "section": "reading-text-1",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 1",
          "shortLabel": "T1",
          "paragraphs": 4,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2019-reading-text-2",
          "section": "reading-text-2",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 2",
          "shortLabel": "T2",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2019-reading-text-3",
          "section": "reading-text-3",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 3",
          "shortLabel": "T3",
          "paragraphs": 7,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2019-reading-text-4",
          "section": "reading-text-4",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 4",
          "shortLabel": "T4",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2019-cloze",
          "section": "cloze",
          "kind": "cloze",
          "kindLabel": "完形",
          "label": "完形填空",
          "shortLabel": "完形",
          "paragraphs": 4,
          "questions": 20,
          "enrichment": 14
        },
        {
          "id": "english-ii-2019-new-question-type",
          "section": "new-question-type",
          "kind": "new-question-type",
          "kindLabel": "新题型",
          "label": "新题型",
          "shortLabel": "新题型",
          "paragraphs": 10,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2019-translation",
          "section": "translation",
          "kind": "translation",
          "kindLabel": "翻译",
          "label": "翻译",
          "shortLabel": "翻译",
          "paragraphs": 1,
          "questions": 1,
          "enrichment": 9
        },
        {
          "id": "english-ii-2019-writing",
          "section": "writing",
          "kind": "writing",
          "kindLabel": "写作",
          "label": "写作",
          "shortLabel": "写作",
          "paragraphs": 0,
          "questions": 0,
          "enrichment": 0
        }
      ]
    },
    {
      "id": "english-ii-2018",
      "track": "english-ii",
      "trackLabel": "英语二",
      "trackShort": "英二",
      "year": 2018,
      "label": "2018 考研英语二",
      "file": "./kaoyan-data/english-ii-2018.js",
      "stats": {
        "sections": 8,
        "paragraphs": 41,
        "questions": 46,
        "words": 2942,
        "enrichment": 23
      },
      "sections": [
        {
          "id": "english-ii-2018-reading-text-1",
          "section": "reading-text-1",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 1",
          "shortLabel": "T1",
          "paragraphs": 8,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2018-reading-text-2",
          "section": "reading-text-2",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 2",
          "shortLabel": "T2",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2018-reading-text-3",
          "section": "reading-text-3",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 3",
          "shortLabel": "T3",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2018-reading-text-4",
          "section": "reading-text-4",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 4",
          "shortLabel": "T4",
          "paragraphs": 6,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2018-cloze",
          "section": "cloze",
          "kind": "cloze",
          "kindLabel": "完形",
          "label": "完形填空",
          "shortLabel": "完形",
          "paragraphs": 3,
          "questions": 20,
          "enrichment": 14
        },
        {
          "id": "english-ii-2018-new-question-type",
          "section": "new-question-type",
          "kind": "new-question-type",
          "kindLabel": "新题型",
          "label": "新题型",
          "shortLabel": "新题型",
          "paragraphs": 12,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2018-translation",
          "section": "translation",
          "kind": "translation",
          "kindLabel": "翻译",
          "label": "翻译",
          "shortLabel": "翻译",
          "paragraphs": 2,
          "questions": 1,
          "enrichment": 9
        },
        {
          "id": "english-ii-2018-writing",
          "section": "writing",
          "kind": "writing",
          "kindLabel": "写作",
          "label": "写作",
          "shortLabel": "写作",
          "paragraphs": 0,
          "questions": 0,
          "enrichment": 0
        }
      ]
    },
    {
      "id": "english-ii-2017",
      "track": "english-ii",
      "trackLabel": "英语二",
      "trackShort": "英二",
      "year": 2017,
      "label": "2017 考研英语二",
      "file": "./kaoyan-data/english-ii-2017.js",
      "stats": {
        "sections": 8,
        "paragraphs": 29,
        "questions": 46,
        "words": 2934,
        "enrichment": 23
      },
      "sections": [
        {
          "id": "english-ii-2017-reading-text-1",
          "section": "reading-text-1",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 1",
          "shortLabel": "T1",
          "paragraphs": 3,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2017-reading-text-2",
          "section": "reading-text-2",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 2",
          "shortLabel": "T2",
          "paragraphs": 3,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2017-reading-text-3",
          "section": "reading-text-3",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 3",
          "shortLabel": "T3",
          "paragraphs": 4,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2017-reading-text-4",
          "section": "reading-text-4",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 4",
          "shortLabel": "T4",
          "paragraphs": 6,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2017-cloze",
          "section": "cloze",
          "kind": "cloze",
          "kindLabel": "完形",
          "label": "完形填空",
          "shortLabel": "完形",
          "paragraphs": 3,
          "questions": 20,
          "enrichment": 14
        },
        {
          "id": "english-ii-2017-new-question-type",
          "section": "new-question-type",
          "kind": "new-question-type",
          "kindLabel": "新题型",
          "label": "新题型",
          "shortLabel": "新题型",
          "paragraphs": 9,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2017-translation",
          "section": "translation",
          "kind": "translation",
          "kindLabel": "翻译",
          "label": "翻译",
          "shortLabel": "翻译",
          "paragraphs": 1,
          "questions": 1,
          "enrichment": 9
        },
        {
          "id": "english-ii-2017-writing",
          "section": "writing",
          "kind": "writing",
          "kindLabel": "写作",
          "label": "写作",
          "shortLabel": "写作",
          "paragraphs": 0,
          "questions": 0,
          "enrichment": 0
        }
      ]
    },
    {
      "id": "english-ii-2016",
      "track": "english-ii",
      "trackLabel": "英语二",
      "trackShort": "英二",
      "year": 2016,
      "label": "2016 考研英语二",
      "file": "./kaoyan-data/english-ii-2016.js",
      "stats": {
        "sections": 8,
        "paragraphs": 32,
        "questions": 46,
        "words": 3339,
        "enrichment": 23
      },
      "sections": [
        {
          "id": "english-ii-2016-reading-text-1",
          "section": "reading-text-1",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 1",
          "shortLabel": "T1",
          "paragraphs": 3,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2016-reading-text-2",
          "section": "reading-text-2",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 2",
          "shortLabel": "T2",
          "paragraphs": 3,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2016-reading-text-3",
          "section": "reading-text-3",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 3",
          "shortLabel": "T3",
          "paragraphs": 6,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2016-reading-text-4",
          "section": "reading-text-4",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 4",
          "shortLabel": "T4",
          "paragraphs": 3,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2016-cloze",
          "section": "cloze",
          "kind": "cloze",
          "kindLabel": "完形",
          "label": "完形填空",
          "shortLabel": "完形",
          "paragraphs": 6,
          "questions": 20,
          "enrichment": 14
        },
        {
          "id": "english-ii-2016-new-question-type",
          "section": "new-question-type",
          "kind": "new-question-type",
          "kindLabel": "新题型",
          "label": "新题型",
          "shortLabel": "新题型",
          "paragraphs": 10,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2016-translation",
          "section": "translation",
          "kind": "translation",
          "kindLabel": "翻译",
          "label": "翻译",
          "shortLabel": "翻译",
          "paragraphs": 1,
          "questions": 1,
          "enrichment": 9
        },
        {
          "id": "english-ii-2016-writing",
          "section": "writing",
          "kind": "writing",
          "kindLabel": "写作",
          "label": "写作",
          "shortLabel": "写作",
          "paragraphs": 0,
          "questions": 0,
          "enrichment": 0
        }
      ]
    },
    {
      "id": "english-ii-2015",
      "track": "english-ii",
      "trackLabel": "英语二",
      "trackShort": "英二",
      "year": 2015,
      "label": "2015 考研英语二",
      "file": "./kaoyan-data/english-ii-2015.js",
      "stats": {
        "sections": 8,
        "paragraphs": 36,
        "questions": 46,
        "words": 3223,
        "enrichment": 23
      },
      "sections": [
        {
          "id": "english-ii-2015-reading-text-1",
          "section": "reading-text-1",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 1",
          "shortLabel": "T1",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2015-reading-text-2",
          "section": "reading-text-2",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 2",
          "shortLabel": "T2",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2015-reading-text-3",
          "section": "reading-text-3",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 3",
          "shortLabel": "T3",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2015-reading-text-4",
          "section": "reading-text-4",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 4",
          "shortLabel": "T4",
          "paragraphs": 4,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2015-cloze",
          "section": "cloze",
          "kind": "cloze",
          "kindLabel": "完形",
          "label": "完形填空",
          "shortLabel": "完形",
          "paragraphs": 5,
          "questions": 20,
          "enrichment": 14
        },
        {
          "id": "english-ii-2015-new-question-type",
          "section": "new-question-type",
          "kind": "new-question-type",
          "kindLabel": "新题型",
          "label": "新题型",
          "shortLabel": "新题型",
          "paragraphs": 9,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2015-translation",
          "section": "translation",
          "kind": "translation",
          "kindLabel": "翻译",
          "label": "翻译",
          "shortLabel": "翻译",
          "paragraphs": 3,
          "questions": 1,
          "enrichment": 9
        },
        {
          "id": "english-ii-2015-writing",
          "section": "writing",
          "kind": "writing",
          "kindLabel": "写作",
          "label": "写作",
          "shortLabel": "写作",
          "paragraphs": 0,
          "questions": 0,
          "enrichment": 0
        }
      ]
    },
    {
      "id": "english-ii-2014",
      "track": "english-ii",
      "trackLabel": "英语二",
      "trackShort": "英二",
      "year": 2014,
      "label": "2014 考研英语二",
      "file": "./kaoyan-data/english-ii-2014.js",
      "stats": {
        "sections": 8,
        "paragraphs": 29,
        "questions": 46,
        "words": 2825,
        "enrichment": 23
      },
      "sections": [
        {
          "id": "english-ii-2014-reading-text-1",
          "section": "reading-text-1",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 1",
          "shortLabel": "T1",
          "paragraphs": 3,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2014-reading-text-2",
          "section": "reading-text-2",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 2",
          "shortLabel": "T2",
          "paragraphs": 3,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2014-reading-text-3",
          "section": "reading-text-3",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 3",
          "shortLabel": "T3",
          "paragraphs": 4,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2014-reading-text-4",
          "section": "reading-text-4",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 4",
          "shortLabel": "T4",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2014-cloze",
          "section": "cloze",
          "kind": "cloze",
          "kindLabel": "完形",
          "label": "完形填空",
          "shortLabel": "完形",
          "paragraphs": 4,
          "questions": 20,
          "enrichment": 14
        },
        {
          "id": "english-ii-2014-new-question-type",
          "section": "new-question-type",
          "kind": "new-question-type",
          "kindLabel": "新题型",
          "label": "新题型",
          "shortLabel": "新题型",
          "paragraphs": 8,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2014-translation",
          "section": "translation",
          "kind": "translation",
          "kindLabel": "翻译",
          "label": "翻译",
          "shortLabel": "翻译",
          "paragraphs": 2,
          "questions": 1,
          "enrichment": 9
        },
        {
          "id": "english-ii-2014-writing",
          "section": "writing",
          "kind": "writing",
          "kindLabel": "写作",
          "label": "写作",
          "shortLabel": "写作",
          "paragraphs": 0,
          "questions": 0,
          "enrichment": 0
        }
      ]
    },
    {
      "id": "english-ii-2013",
      "track": "english-ii",
      "trackLabel": "英语二",
      "trackShort": "英二",
      "year": 2013,
      "label": "2013 考研英语二",
      "file": "./kaoyan-data/english-ii-2013.js",
      "stats": {
        "sections": 8,
        "paragraphs": 32,
        "questions": 46,
        "words": 2860,
        "enrichment": 23
      },
      "sections": [
        {
          "id": "english-ii-2013-reading-text-1",
          "section": "reading-text-1",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 1",
          "shortLabel": "T1",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2013-reading-text-2",
          "section": "reading-text-2",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 2",
          "shortLabel": "T2",
          "paragraphs": 4,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2013-reading-text-3",
          "section": "reading-text-3",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 3",
          "shortLabel": "T3",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2013-reading-text-4",
          "section": "reading-text-4",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 4",
          "shortLabel": "T4",
          "paragraphs": 6,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2013-cloze",
          "section": "cloze",
          "kind": "cloze",
          "kindLabel": "完形",
          "label": "完形填空",
          "shortLabel": "完形",
          "paragraphs": 3,
          "questions": 20,
          "enrichment": 14
        },
        {
          "id": "english-ii-2013-new-question-type",
          "section": "new-question-type",
          "kind": "new-question-type",
          "kindLabel": "新题型",
          "label": "新题型",
          "shortLabel": "新题型",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2013-translation",
          "section": "translation",
          "kind": "translation",
          "kindLabel": "翻译",
          "label": "翻译",
          "shortLabel": "翻译",
          "paragraphs": 4,
          "questions": 1,
          "enrichment": 9
        },
        {
          "id": "english-ii-2013-writing",
          "section": "writing",
          "kind": "writing",
          "kindLabel": "写作",
          "label": "写作",
          "shortLabel": "写作",
          "paragraphs": 0,
          "questions": 0,
          "enrichment": 0
        }
      ]
    },
    {
      "id": "english-ii-2012",
      "track": "english-ii",
      "trackLabel": "英语二",
      "trackShort": "英二",
      "year": 2012,
      "label": "2012 考研英语二",
      "file": "./kaoyan-data/english-ii-2012.js",
      "stats": {
        "sections": 8,
        "paragraphs": 27,
        "questions": 46,
        "words": 2966,
        "enrichment": 23
      },
      "sections": [
        {
          "id": "english-ii-2012-reading-text-1",
          "section": "reading-text-1",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 1",
          "shortLabel": "T1",
          "paragraphs": 3,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2012-reading-text-2",
          "section": "reading-text-2",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 2",
          "shortLabel": "T2",
          "paragraphs": 6,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2012-reading-text-3",
          "section": "reading-text-3",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 3",
          "shortLabel": "T3",
          "paragraphs": 4,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2012-reading-text-4",
          "section": "reading-text-4",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 4",
          "shortLabel": "T4",
          "paragraphs": 4,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2012-cloze",
          "section": "cloze",
          "kind": "cloze",
          "kindLabel": "完形",
          "label": "完形填空",
          "shortLabel": "完形",
          "paragraphs": 3,
          "questions": 20,
          "enrichment": 14
        },
        {
          "id": "english-ii-2012-new-question-type",
          "section": "new-question-type",
          "kind": "new-question-type",
          "kindLabel": "新题型",
          "label": "新题型",
          "shortLabel": "新题型",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2012-translation",
          "section": "translation",
          "kind": "translation",
          "kindLabel": "翻译",
          "label": "翻译",
          "shortLabel": "翻译",
          "paragraphs": 2,
          "questions": 1,
          "enrichment": 9
        },
        {
          "id": "english-ii-2012-writing",
          "section": "writing",
          "kind": "writing",
          "kindLabel": "写作",
          "label": "写作",
          "shortLabel": "写作",
          "paragraphs": 0,
          "questions": 0,
          "enrichment": 0
        }
      ]
    },
    {
      "id": "english-ii-2011",
      "track": "english-ii",
      "trackLabel": "英语二",
      "trackShort": "英二",
      "year": 2011,
      "label": "2011 考研英语二",
      "file": "./kaoyan-data/english-ii-2011.js",
      "stats": {
        "sections": 8,
        "paragraphs": 35,
        "questions": 46,
        "words": 2940,
        "enrichment": 23
      },
      "sections": [
        {
          "id": "english-ii-2011-reading-text-1",
          "section": "reading-text-1",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 1",
          "shortLabel": "T1",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2011-reading-text-2",
          "section": "reading-text-2",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 2",
          "shortLabel": "T2",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2011-reading-text-3",
          "section": "reading-text-3",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 3",
          "shortLabel": "T3",
          "paragraphs": 4,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2011-reading-text-4",
          "section": "reading-text-4",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 4",
          "shortLabel": "T4",
          "paragraphs": 4,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2011-cloze",
          "section": "cloze",
          "kind": "cloze",
          "kindLabel": "完形",
          "label": "完形填空",
          "shortLabel": "完形",
          "paragraphs": 5,
          "questions": 20,
          "enrichment": 14
        },
        {
          "id": "english-ii-2011-new-question-type",
          "section": "new-question-type",
          "kind": "new-question-type",
          "kindLabel": "新题型",
          "label": "新题型",
          "shortLabel": "新题型",
          "paragraphs": 9,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2011-translation",
          "section": "translation",
          "kind": "translation",
          "kindLabel": "翻译",
          "label": "翻译",
          "shortLabel": "翻译",
          "paragraphs": 3,
          "questions": 1,
          "enrichment": 9
        },
        {
          "id": "english-ii-2011-writing",
          "section": "writing",
          "kind": "writing",
          "kindLabel": "写作",
          "label": "写作",
          "shortLabel": "写作",
          "paragraphs": 0,
          "questions": 0,
          "enrichment": 0
        }
      ]
    },
    {
      "id": "english-ii-2010",
      "track": "english-ii",
      "trackLabel": "英语二",
      "trackShort": "英二",
      "year": 2010,
      "label": "2010 考研英语二",
      "file": "./kaoyan-data/english-ii-2010.js",
      "stats": {
        "sections": 8,
        "paragraphs": 32,
        "questions": 46,
        "words": 3051,
        "enrichment": 23
      },
      "sections": [
        {
          "id": "english-ii-2010-reading-text-1",
          "section": "reading-text-1",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 1",
          "shortLabel": "T1",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2010-reading-text-2",
          "section": "reading-text-2",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 2",
          "shortLabel": "T2",
          "paragraphs": 5,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2010-reading-text-3",
          "section": "reading-text-3",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 3",
          "shortLabel": "T3",
          "paragraphs": 4,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2010-reading-text-4",
          "section": "reading-text-4",
          "kind": "reading",
          "kindLabel": "阅读",
          "label": "阅读 Text 4",
          "shortLabel": "T4",
          "paragraphs": 3,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2010-cloze",
          "section": "cloze",
          "kind": "cloze",
          "kindLabel": "完形",
          "label": "完形填空",
          "shortLabel": "完形",
          "paragraphs": 4,
          "questions": 20,
          "enrichment": 14
        },
        {
          "id": "english-ii-2010-new-question-type",
          "section": "new-question-type",
          "kind": "new-question-type",
          "kindLabel": "新题型",
          "label": "新题型",
          "shortLabel": "新题型",
          "paragraphs": 7,
          "questions": 5,
          "enrichment": 0
        },
        {
          "id": "english-ii-2010-translation",
          "section": "translation",
          "kind": "translation",
          "kindLabel": "翻译",
          "label": "翻译",
          "shortLabel": "翻译",
          "paragraphs": 4,
          "questions": 1,
          "enrichment": 9
        },
        {
          "id": "english-ii-2010-writing",
          "section": "writing",
          "kind": "writing",
          "kindLabel": "写作",
          "label": "写作",
          "shortLabel": "写作",
          "paragraphs": 0,
          "questions": 0,
          "enrichment": 0
        }
      ]
    }
  ]
};
