// Generated by scripts/build-movie-library.mjs
window.IBALL_MOVIE_EPISODES = [
  {
    "id": "S01E24",
    "label": "S01E24",
    "title": "Modern Family S01E24",
    "file": "./movie-data/S01E24.js",
    "blockCount": 453,
    "wordCount": 0,
    "vocabCount": 787,
    "sceneCount": 12,
    "translationStats": {
      "curated": 0,
      "card": 0,
      "reviewed": 453,
      "machine": 0,
      "missing": 0
    }
  },
  {
    "id": "S01E23",
    "label": "S01E23",
    "title": "Modern Family S01E23",
    "file": "./movie-data/S01E23.js",
    "blockCount": 484,
    "wordCount": 0,
    "vocabCount": 841,
    "sceneCount": 12,
    "translationStats": {
      "curated": 0,
      "card": 0,
      "reviewed": 484,
      "machine": 0,
      "missing": 0
    }
  },
  {
    "id": "S01E22",
    "label": "S01E22",
    "title": "Modern Family S01E22",
    "file": "./movie-data/S01E22.js",
    "blockCount": 473,
    "wordCount": 0,
    "vocabCount": 849,
    "sceneCount": 11,
    "translationStats": {
      "curated": 0,
      "card": 0,
      "reviewed": 473,
      "machine": 0,
      "missing": 0
    }
  },
  {
    "id": "S01E21",
    "label": "S01E21",
    "title": "Modern Family S01E21",
    "file": "./movie-data/S01E21.js",
    "blockCount": 454,
    "wordCount": 0,
    "vocabCount": 824,
    "sceneCount": 12,
    "translationStats": {
      "curated": 0,
      "card": 0,
      "reviewed": 454,
      "machine": 0,
      "missing": 0
    }
  },
  {
    "id": "S01E20",
    "label": "S01E20",
    "title": "Modern Family S01E20",
    "file": "./movie-data/S01E20.js",
    "blockCount": 491,
    "wordCount": 0,
    "vocabCount": 832,
    "sceneCount": 11,
    "translationStats": {
      "curated": 0,
      "card": 0,
      "reviewed": 491,
      "machine": 0,
      "missing": 0
    }
  },
  {
    "id": "S01E19",
    "label": "S01E19",
    "title": "Modern Family S01E19",
    "file": "./movie-data/S01E19.js",
    "blockCount": 495,
    "wordCount": 0,
    "vocabCount": 832,
    "sceneCount": 12,
    "translationStats": {
      "curated": 0,
      "card": 0,
      "reviewed": 495,
      "machine": 0,
      "missing": 0
    }
  },
  {
    "id": "S01E18",
    "label": "S01E18",
    "title": "Modern Family S01E18",
    "file": "./movie-data/S01E18.js",
    "blockCount": 467,
    "wordCount": 0,
    "vocabCount": 824,
    "sceneCount": 12,
    "translationStats": {
      "curated": 0,
      "card": 0,
      "reviewed": 467,
      "machine": 0,
      "missing": 0
    }
  },
  {
    "id": "S01E17",
    "label": "S01E17",
    "title": "Modern Family S01E17",
    "file": "./movie-data/S01E17.js",
    "blockCount": 505,
    "wordCount": 0,
    "vocabCount": 856,
    "sceneCount": 12,
    "translationStats": {
      "curated": 0,
      "card": 0,
      "reviewed": 505,
      "machine": 0,
      "missing": 0
    }
  },
  {
    "id": "S01E16",
    "label": "S01E16",
    "title": "Modern Family S01E16",
    "file": "./movie-data/S01E16.js",
    "blockCount": 463,
    "wordCount": 0,
    "vocabCount": 842,
    "sceneCount": 11,
    "translationStats": {
      "curated": 0,
      "card": 0,
      "reviewed": 463,
      "machine": 0,
      "missing": 0
    }
  },
  {
    "id": "S01E15",
    "label": "S01E15",
    "title": "Modern Family S01E15",
    "file": "./movie-data/S01E15.js",
    "blockCount": 490,
    "wordCount": 0,
    "vocabCount": 825,
    "sceneCount": 12,
    "translationStats": {
      "curated": 0,
      "card": 0,
      "reviewed": 490,
      "machine": 0,
      "missing": 0
    }
  },
  {
    "id": "S01E14",
    "label": "S01E14",
    "title": "Modern Family S01E14",
    "file": "./movie-data/S01E14.js",
    "blockCount": 504,
    "wordCount": 0,
    "vocabCount": 909,
    "sceneCount": 12,
    "translationStats": {
      "curated": 0,
      "card": 0,
      "reviewed": 504,
      "machine": 0,
      "missing": 0
    }
  },
  {
    "id": "S01E13",
    "label": "S01E13",
    "title": "Modern Family S01E13",
    "file": "./movie-data/S01E13.js",
    "blockCount": 503,
    "wordCount": 0,
    "vocabCount": 842,
    "sceneCount": 12,
    "translationStats": {
      "curated": 0,
      "card": 0,
      "reviewed": 503,
      "machine": 0,
      "missing": 0
    }
  },
  {
    "id": "S01E12",
    "label": "S01E12",
    "title": "Modern Family S01E12",
    "file": "./movie-data/S01E12.js",
    "blockCount": 477,
    "wordCount": 0,
    "vocabCount": 850,
    "sceneCount": 12,
    "translationStats": {
      "curated": 0,
      "card": 0,
      "reviewed": 477,
      "machine": 0,
      "missing": 0
    }
  },
  {
    "id": "S01E11",
    "label": "S01E11",
    "title": "Modern Family S01E11",
    "file": "./movie-data/S01E11.js",
    "blockCount": 527,
    "wordCount": 0,
    "vocabCount": 866,
    "sceneCount": 12,
    "translationStats": {
      "curated": 0,
      "card": 0,
      "reviewed": 527,
      "machine": 0,
      "missing": 0
    }
  },
  {
    "id": "S01E10",
    "label": "S01E10",
    "title": "Modern Family S01E10",
    "file": "./movie-data/S01E10.js",
    "blockCount": 492,
    "wordCount": 0,
    "vocabCount": 790,
    "sceneCount": 12,
    "translationStats": {
      "curated": 0,
      "card": 0,
      "reviewed": 492,
      "machine": 0,
      "missing": 0
    }
  },
  {
    "id": "S01E09",
    "label": "S01E09",
    "title": "Modern Family S01E09",
    "file": "./movie-data/S01E09.js",
    "blockCount": 469,
    "wordCount": 0,
    "vocabCount": 833,
    "sceneCount": 11,
    "translationStats": {
      "curated": 0,
      "card": 0,
      "reviewed": 469,
      "machine": 0,
      "missing": 0
    }
  },
  {
    "id": "S01E08",
    "label": "S01E08",
    "title": "Modern Family S01E08",
    "file": "./movie-data/S01E08.js",
    "blockCount": 478,
    "wordCount": 0,
    "vocabCount": 820,
    "sceneCount": 12,
    "translationStats": {
      "curated": 0,
      "card": 0,
      "reviewed": 478,
      "machine": 0,
      "missing": 0
    }
  },
  {
    "id": "S01E07",
    "label": "S01E07",
    "title": "Modern Family S01E07",
    "file": "./movie-data/S01E07.js",
    "blockCount": 414,
    "wordCount": 0,
    "vocabCount": 809,
    "sceneCount": 11,
    "translationStats": {
      "curated": 0,
      "card": 0,
      "reviewed": 414,
      "machine": 0,
      "missing": 0
    }
  },
  {
    "id": "S01E06",
    "label": "S01E06",
    "title": "Modern Family S01E06",
    "file": "./movie-data/S01E06.js",
    "blockCount": 500,
    "wordCount": 0,
    "vocabCount": 902,
    "sceneCount": 11,
    "translationStats": {
      "curated": 0,
      "card": 0,
      "reviewed": 500,
      "machine": 0,
      "missing": 0
    }
  },
  {
    "id": "S01E05",
    "label": "S01E05",
    "title": "Modern Family S01E05",
    "file": "./movie-data/S01E05.js",
    "blockCount": 511,
    "wordCount": 0,
    "vocabCount": 814,
    "sceneCount": 11,
    "translationStats": {
      "curated": 0,
      "card": 0,
      "reviewed": 511,
      "machine": 0,
      "missing": 0
    }
  },
  {
    "id": "S01E04",
    "label": "S01E04",
    "title": "Modern Family S01E04",
    "file": "./movie-data/S01E04.js",
    "blockCount": 509,
    "wordCount": 0,
    "vocabCount": 791,
    "sceneCount": 12,
    "translationStats": {
      "curated": 0,
      "card": 0,
      "reviewed": 509,
      "machine": 0,
      "missing": 0
    }
  },
  {
    "id": "S01E03",
    "label": "S01E03",
    "title": "Modern Family S01E03",
    "file": "./movie-data/S01E03.js",
    "blockCount": 465,
    "wordCount": 0,
    "vocabCount": 767,
    "sceneCount": 11,
    "translationStats": {
      "curated": 0,
      "card": 0,
      "reviewed": 465,
      "machine": 0,
      "missing": 0
    }
  },
  {
    "id": "S01E02",
    "label": "S01E02",
    "title": "Modern Family S01E02",
    "file": "./movie-data/S01E02.js",
    "blockCount": 457,
    "wordCount": 0,
    "vocabCount": 828,
    "sceneCount": 12,
    "translationStats": {
      "curated": 95,
      "card": 0,
      "reviewed": 290,
      "machine": 0,
      "missing": 0
    }
  },
  {
    "id": "S01E01",
    "label": "S01E01",
    "title": "Modern Family S01E01",
    "file": "./movie-data/S01E01.js",
    "blockCount": 496,
    "wordCount": 0,
    "vocabCount": 835,
    "sceneCount": 15,
    "translationStats": {
      "curated": 89,
      "card": 12,
      "reviewed": 228,
      "machine": 0,
      "missing": 0
    }
  }
];
