// Generated by scripts/build-movie-library.mjs
window.IBALL_MOVIE_EPISODES = [
  {
    "id": "S01E01",
    "label": "S01E01",
    "title": "Modern Family S01E01",
    "file": "./movie-data/S01E01.js",
    "blockCount": 461,
    "wordCount": 3675,
    "sceneCount": 15,
    "translationStats": {
      "curated": 85,
      "card": 12,
      "machine": 218,
      "missing": 0
    }
  }
];
